"""Small reviewed UI catalogue; content replies follow the selected language."""
STRINGS = {
"en": ["Your desktop learning companion", "Conversation", "My files", "Learn & research", "AI services", "Settings", "Ask LAFA…", "Send", "Listen · 8s", "Read aloud", "Online", "Offline · LAFA is paused", "Find", "Open", "Read document", "Search topic…", "Search filename…", "All files", "Documents", "Music", "Videos", "Pictures", "Provider", "Model ID", "API key", "Save settings", "Show desktop companion", "Allow walking on desktop", "Read answers aloud", "Language", "New conversation", "I’m LAFA. What would you like to learn today?", "I can help you learn, find your files, explore sources, and talk things through.", "Internet is required. Connect to resume LAFA.", "AI replies need an API key and a model in Settings. Search and AI service links are available without a key.", "Open / sign in", "Search on web", "Send this document to AI?", "Selected text will be sent to your selected provider. Review it first.", "Secure keyring", "Add folder", "Remove folder", "Ready", "Working…", "Stop voice", "Local document preview", "Summarize with AI", "API requests may use paid credits. Browser sign-in is separate.", "Pause animations", "Show LAFA", "Quit", "Supported files: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Results", "No matching files.", "Search stopped at its time or result limit; narrow the query.", "Export conversation", "Clear saved key", "Mood", "Idle", "Reading", "Thinking", "Walking", "Sitting", "Gaming", "Serious", "Angry", "Talking"],
"id": ["Teman belajar di desktop Anda", "Percakapan", "File saya", "Belajar & riset", "Layanan AI", "Pengaturan", "Tanya LAFA…", "Kirim", "Dengarkan · 8 dtk", "Baca bersuara", "Terhubung", "Offline · LAFA dijeda", "Cari", "Buka", "Baca dokumen", "Cari topik…", "Cari nama file…", "Semua file", "Dokumen", "Musik", "Video", "Gambar", "Penyedia", "ID model", "API key", "Simpan pengaturan", "Tampilkan karakter desktop", "Izinkan berjalan di desktop", "Bacakan jawaban", "Bahasa", "Percakapan baru", "Saya LAFA. Apa yang ingin Anda pelajari hari ini?", "Saya bisa membantu belajar, mencari file, menelusuri sumber, dan mendengarkan cerita Anda.", "Internet diperlukan. Hubungkan untuk melanjutkan LAFA.", "Jawaban AI memerlukan API key dan model di Pengaturan. Pencarian dan tautan layanan AI tersedia tanpa key.", "Buka / login", "Cari di web", "Kirim dokumen ini ke AI?", "Teks yang dipilih akan dikirim ke penyedia Anda. Tinjau terlebih dahulu.", "Keyring aman", "Tambah folder", "Hapus folder", "Siap", "Sedang bekerja…", "Hentikan suara", "Pratinjau dokumen lokal", "Ringkas dengan AI", "Permintaan API dapat memakai kredit berbayar. Login browser terpisah.", "Jeda animasi", "Tampilkan LAFA", "Keluar", "Format: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Hasil", "Tidak ada file yang cocok.", "Pencarian mencapai batas waktu atau hasil; persempit kata pencarian.", "Ekspor percakapan", "Hapus key tersimpan", "Ekspresi", "Santai", "Membaca", "Berpikir", "Berjalan", "Duduk", "Bermain", "Serius", "Marah", "Berbicara"],
"pt": ["O seu companheiro de aprendizagem", "Conversa", "Os meus ficheiros", "Aprender e pesquisar", "Serviços de IA", "Definições", "Pergunte ao LAFA…", "Enviar", "Ouvir · 8s", "Ler em voz alta", "Ligado", "Sem internet · LAFA em pausa", "Procurar", "Abrir", "Ler documento", "Procurar tema…", "Procurar ficheiro…", "Todos os ficheiros", "Documentos", "Música", "Vídeos", "Imagens", "Fornecedor", "ID do modelo", "Chave API", "Guardar definições", "Mostrar personagem no ambiente de trabalho", "Permitir caminhar", "Ler respostas em voz alta", "Idioma", "Nova conversa", "Sou o LAFA. O que gostaria de aprender hoje?", "Posso ajudar a aprender, encontrar ficheiros, explorar fontes e conversar.", "É necessária internet. Ligue-se para continuar.", "As respostas de IA precisam de chave API e modelo nas Definições. A pesquisa e os links funcionam sem chave.", "Abrir / iniciar sessão", "Pesquisar na web", "Enviar este documento à IA?", "O texto selecionado será enviado ao fornecedor. Reveja-o primeiro.", "Porta-chaves seguro", "Adicionar pasta", "Remover pasta", "Pronto", "A trabalhar…", "Parar voz", "Pré-visualização local", "Resumir com IA", "A API pode utilizar créditos pagos. O início de sessão no navegador é separado.", "Pausar animações", "Mostrar LAFA", "Sair", "Formatos: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Resultados", "Nenhum ficheiro encontrado.", "A pesquisa atingiu o limite; reduza o âmbito.", "Exportar conversa", "Apagar chave guardada", "Expressão", "Tranquilo", "A ler", "A pensar", "A caminhar", "Sentado", "A jogar", "Sério", "Zangado", "A falar"],
"tet": ["Ita-nia belun aprendizajen iha desktop", "Konversa", "Ha'u-nia ficheiru", "Aprende no peskiza", "Servisu AI", "Konfigurasaun", "Husu LAFA…", "Haruka", "Rona · 8s", "Lee ho lian", "Konektadu", "Internet la iha · LAFA para", "Buka", "Loke", "Lee dokumentu", "Buka tópiku…", "Buka naran ficheiru…", "Ficheiru hotu", "Dokumentu", "Múzika", "Vídeu", "Imajen", "Fornesedór", "ID modelu", "Xave API", "Rai konfigurasaun", "Hatudu karakter iha desktop", "Permite la'o iha desktop", "Lee resposta ho lian", "Lian", "Konversa foun", "Ha'u LAFA. Ita hakarak aprende saida ohin?", "Ha'u bele ajuda aprende, buka ficheiru, peskiza fonte no rona ita-nia istória.", "Presiza internet. Konekta atu kontinua LAFA.", "Resposta AI presiza xave API no modelu iha Konfigurasaun. Peskiza no ligasaun AI bele uza sein xave.", "Loke / tama konta", "Buka iha web", "Haruka dokumentu ne'e ba AI?", "Testu ne'ebé hili sei haruka ba fornesedór. Haree uluk.", "Keyring seguru", "Aumenta pasta", "Hasai pasta", "Prontu", "Halo hela…", "Para lian", "Haree dokumentu lokál", "Halo rezumu ho AI", "API bele uza kréditu selu. Login iha browser ketak.", "Para animasaun", "Hatudu LAFA", "Sai", "Formatu: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Rezultadu", "La hetan ficheiru.", "Peskiza to'o limite; hatún ámbitu.", "Esporta konversa", "Hasai xave rai", "Espresaun", "Kalmu", "Lee hela", "Hanoin hela", "La'o hela", "Tuur", "Joga hela", "Sériu", "Hirus", "Ko'alia"],
}
KEYS = ["tagline","chat","files","learn","hub","settings","ask","send","listen","speak","online","offline","find","open","read","topic","filename","all","documents","music","videos","pictures","provider","model","key","save","companion","roam","autoread","language","new","hello","intro","neednet","needkey","login","web","confirmdoc","confirmtext","keyring","addfolder","removefolder","ready","working","stopvoice","preview","summarize","cost","pause","show","quit","formats","results","empty","limited","export","clearkey","mood","idle","reading","thinking","walking","sitting","gaming","serious","angry","talking"]


EXTRA = {
'en':{'virtual':'Desktop assistant','live':'Weather & news','weather':'Weather','news':'World news','reminders':'Reminders','focus':'Focus · 25 min','fullwindow':'Full window','hide':'Hide bubble','sleeping':'Sleeping','bathing':'Bathing','toilet':'Toilet','studying':'Studying','eating':'Eating','stretching':'Stretching','city':'Home city','coords':'Coordinates (lat, lon)','personal':'Include bathing / toilet activities','idlehelp':'Idle activities change every 60 seconds.','addreminder':'Add reminder','minutes':'Minutes','remindertext':'What should I remind you about?','cancelreminder':'Cancel selected','sessionreminder':'Reminders work while LAFA is running; they are not saved after exit.','choosecity':'Choose the exact location','source_search':'Search a selected site','details':'Details / sources','welcome_desktop':'Hi, I’m LAFA, your Edukasaun OS assistant. Ask a question or choose weather, news, or focus.'},
'id':{'virtual':'Asisten desktop','live':'Cuaca & berita','weather':'Cuaca','news':'Berita dunia','reminders':'Pengingat','focus':'Fokus · 25 menit','fullwindow':'Jendela lengkap','hide':'Tutup balon','sleeping':'Tidur','bathing':'Mandi','toilet':'Toilet','studying':'Belajar','eating':'Makan','stretching':'Peregangan','city':'Kota utama','coords':'Koordinat (lat, lon)','personal':'Sertakan aktivitas mandi / toilet','idlehelp':'Aktivitas berganti setiap 60 detik saat tidak digunakan.','addreminder':'Tambah pengingat','minutes':'Menit','remindertext':'Apa yang perlu saya ingatkan?','cancelreminder':'Batalkan pilihan','sessionreminder':'Pengingat bekerja selama LAFA berjalan; tidak disimpan setelah keluar.','choosecity':'Pilih lokasi yang tepat','source_search':'Cari di situs pilihan','details':'Detail / sumber','welcome_desktop':'Halo, saya LAFA, asisten Edukasaun OS Anda. Tanyakan sesuatu atau pilih cuaca, berita, atau fokus.'},
'pt':{'virtual':'Assistente no desktop','live':'Tempo e notícias','weather':'Tempo','news':'Notícias do mundo','reminders':'Lembretes','focus':'Foco · 25 min','fullwindow':'Janela completa','hide':'Fechar balão','sleeping':'A dormir','bathing':'A tomar banho','toilet':'Casa de banho','studying':'A estudar','eating':'A comer','stretching':'Alongamentos','city':'Cidade principal','coords':'Coordenadas (lat, lon)','personal':'Incluir banho / casa de banho','idlehelp':'As atividades mudam a cada 60 segundos de inatividade.','addreminder':'Adicionar lembrete','minutes':'Minutos','remindertext':'O que devo lembrar?','cancelreminder':'Cancelar seleção','sessionreminder':'Lembretes funcionam enquanto o LAFA está aberto; não são guardados após sair.','choosecity':'Escolha a localização exata','source_search':'Pesquisar no site escolhido','details':'Detalhes / fontes','welcome_desktop':'Olá, sou o LAFA, o seu assistente Edukasaun OS. Pergunte ou escolha tempo, notícias ou foco.'},
'tet':{'virtual':'Asistente desktop','live':'Tempu no notísia','weather':'Tempu','news':'Notísia mundu','reminders':'Lembransa','focus':'Foku · 25 min','fullwindow':'Janela kompletu','hide':'Taka balaun','sleeping':'Toba','bathing':'Hariis','toilet':'Toalete','studying':'Estuda','eating':'Han','stretching':'Estika isin','city':'Sidade prinsipál','coords':'Koordenada (lat, lon)','personal':'Inklui hariis / toalete','idlehelp':'Atividade troka kada 60 segundu bainhira la uza.','addreminder':'Aumenta lembransa','minutes':'Minutu','remindertext':'Presiza fó lembransa kona-ba saida?','cancelreminder':'Kansela hili','sessionreminder':'Lembransa funsiona bainhira LAFA loke; la rai depois sai.','choosecity':'Hili fatin ne’ebé loos','source_search':'Buka iha sítiu hili','details':'Detallu / fonte','welcome_desktop':'Olá, ha’u LAFA, ita-nia asistente Edukasaun OS. Husu ka hili tempu, notísia ka foku.'},
}

# Desktop/Virtual surface strings; executable source and build documentation use English.
NEW={
'en':{'desktop':'LAFA Desktop','virtual':'LAFA Virtual Assistant','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Activate LAFA Virtual Assistant in Eduka-Desktop','traditional':'Timor-Leste traditional outfit','casual':'Casual outfit','costume':'Outfit','system_language':'System default','culture':'Discover Timor-Leste','timor_news':'Timor-Leste news','coding':'Virtual Coding','run_lesson':'Run Python lesson','lesson_mode':'Bounded Python lessons: variables, arithmetic, lists, loops, conditions. No imports, files, network or system commands. JavaScript, HTML and CSS support learning and export.','save_code':'Export code','explain_code':'Explain with AI','source_mode':'Open-source knowledge mode · public source extracts, not model-generated reasoning.','positive':'Positive messages','culture_cards':'Timor-Leste knowledge cards','local_updates':'Timor-Leste news updates','panel_walk':'Walk back and forth above the panel','panel_edge':'Panel edge','panel_height':'Panel height (px)','card_interval':'Cards / positive messages (minutes)','news_interval':'News interval (minutes)','welcome_virtual':'I’m LAFA, from Timor-Leste, a virtual assistant ready to help you. Let’s learn and discover together!','learning_ready':'Ready to learn.','priority':'Priority topics','education':'Education','arts_culture':'Arts & culture','development':'Development','technology':'Technology','open_settings':'Open LAFA settings','source':'Source','source_dates':'Source-linked cards checked on 6 October 2026. Explore more online.','refresh':'Refresh','pause_popups':'Cards and positive messages appear only when LAFA is idle.','disabled_virtual':'Virtual Assistant is disabled. Enable it in LAFA · Eduka-Settings.','tebe':'Tebe-tebe dance','bidu':'Bidu dance'},
'id':{'desktop':'LAFA Desktop','virtual':'LAFA Asisten Virtual','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Aktifkan LAFA Asisten Virtual di Eduka-Desktop','traditional':'Pakaian adat Timor-Leste','casual':'Pakaian santai','costume':'Pakaian','system_language':'Bahasa sistem','culture':'Kenali Timor-Leste','timor_news':'Berita Timor-Leste','coding':'Coding Virtual','run_lesson':'Jalankan pelajaran Python','lesson_mode':'Python terbatas: variabel, aritmetika, daftar, perulangan, kondisi. Tanpa impor, file, jaringan atau perintah sistem. JavaScript, HTML dan CSS untuk belajar dan ekspor.','save_code':'Ekspor kode','explain_code':'Jelaskan dengan AI','source_mode':'Mode pengetahuan sumber terbuka · cuplikan sumber publik, tanpa penalaran model AI.','positive':'Pesan positif','culture_cards':'Kartu pengetahuan Timor-Leste','local_updates':'Pembaruan berita Timor-Leste','panel_walk':'Berjalan bolak-balik di atas panel','panel_edge':'Sisi panel','panel_height':'Tinggi panel (px)','card_interval':'Kartu / pesan positif (menit)','news_interval':'Interval berita (menit)','welcome_virtual':'Saya LAFA, dari Timor-Leste, asisten virtual yang siap membantu Anda. Mari belajar dan menjelajah bersama!','learning_ready':'Siap belajar.','priority':'Topik utama','education':'Pendidikan','arts_culture':'Seni & budaya','development':'Pembangunan','technology':'Teknologi','open_settings':'Buka pengaturan LAFA','source':'Sumber','source_dates':'Kartu bersumber diperiksa pada 6 Oktober 2026. Jelajahi lebih lanjut di internet.','refresh':'Perbarui','pause_popups':'Kartu dan pesan positif muncul hanya saat LAFA tidak digunakan.','disabled_virtual':'Asisten Virtual dinonaktifkan. Aktifkan melalui LAFA · Eduka-Settings.','tebe':'Tari Tebe-tebe','bidu':'Tari Bidu'},
'pt':{'desktop':'LAFA Desktop','virtual':'Assistente Virtual LAFA','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Ativar o Assistente Virtual LAFA no Eduka-Desktop','traditional':'Traje tradicional de Timor-Leste','casual':'Traje informal','costume':'Traje','system_language':'Idioma do sistema','culture':'Conhecer Timor-Leste','timor_news':'Notícias de Timor-Leste','coding':'Programação Virtual','run_lesson':'Executar lição Python','lesson_mode':'Python limitado: variáveis, aritmética, listas, ciclos e condições. Sem importações, ficheiros, rede ou comandos de sistema. JavaScript, HTML e CSS para aprender e exportar.','save_code':'Exportar código','explain_code':'Explicar com IA','source_mode':'Modo de conhecimento aberto · excertos de fontes públicas, sem raciocínio de um modelo.','positive':'Mensagens positivas','culture_cards':'Cartões sobre Timor-Leste','local_updates':'Atualizações de notícias timorenses','panel_walk':'Caminhar junto ao painel','panel_edge':'Posição do painel','panel_height':'Altura do painel (px)','card_interval':'Cartões / mensagens (minutos)','news_interval':'Intervalo de notícias (minutos)','welcome_virtual':'Sou o LAFA, de Timor-Leste, um assistente virtual pronto para ajudar. Vamos aprender e descobrir juntos!','learning_ready':'Pronto para aprender.','priority':'Temas prioritários','education':'Educação','arts_culture':'Arte e cultura','development':'Desenvolvimento','technology':'Tecnologia','open_settings':'Abrir definições LAFA','source':'Fonte','source_dates':'Fontes verificadas em 6 de outubro de 2026. Explore mais online.','refresh':'Atualizar','pause_popups':'Cartões e mensagens aparecem apenas durante a inatividade.','disabled_virtual':'Assistente Virtual desativado. Ative em LAFA · Eduka-Settings.','tebe':'Dança Tebe-tebe','bidu':'Dança Bidu'},
 'tet':{'desktop':'LAFA Desktop','virtual':'LAFA Asistente Virtuál','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Ativa LAFA Asistente Virtuál iha Eduka-Desktop','traditional':'Hatais tradisionál Timor-Leste','casual':'Hatais simples','costume':'Hatais','system_language':'Lian sistema nian','culture':'Koñese Timor-Leste','timor_news':'Notísia Timor-Leste','coding':'Kodifikasaun Virtuál','run_lesson':'Halo lisaun Python','lesson_mode':'Python ho limite: variavel, aritmétika, lista, siklu no kondisaun. La iha importasaun, ficheiru, rede ka komandu sistema. JavaScript, HTML no CSS ba aprende no esporta.','save_code':'Esporta kódigu','explain_code':'Esplika ho AI','source_mode':'Koñesimentu fonte aberta · testu fonte públika, sein modelu AI.','positive':'Mensajen pozitivu','culture_cards':'Karta koñesimentu Timor-Leste','local_updates':'Atualizasaun notísia Timor-Leste','panel_walk':'La’o ba-mai iha painel leten','panel_edge':'Pozisaun painel','panel_height':'Altura painel (px)','card_interval':'Karta / mensajen (minutu)','news_interval':'Intervalu notísia (minutu)','welcome_virtual':'Ha’u LAFA, husi Timor-Leste, asistente virtuál ne’ebé prontu atu ajuda ita. Mai aprende no deskobre hamutuk!','learning_ready':'Prontu atu aprende.','priority':'Tópiku prinsipál','education':'Edukasaun','arts_culture':'Arte no kultura','development':'Dezenvolvimentu','technology':'Teknolojia','open_settings':'Loke konfigurasaun LAFA','source':'Fonte','source_dates':'Fonte verifika iha 6 Outubru 2026. Buka tan iha internet.','refresh':'Atualiza','pause_popups':'Karta no mensajen mosu de’it bainhira LAFA la uza.','disabled_virtual':'Asistente Virtuál la ativu. Ativa iha LAFA · Eduka-Settings.','tebe':'Dansa Tebe-tebe','bidu':'Dansa Bidu'}
}

# Common interface text (prototype series). Translations are data, not executable code.
RELEASE={
'en':{
'public_search':'Search public sources','public_hint':'Send this question to Wikipedia. Use public topics; do not include private information.',
'source_help':'I can help you find public sources, read documents, check weather and news, and practice coding without an AI key. For a public question, use Search public sources or /ask topic. Your ordinary chat text is not automatically sent to Wikipedia. A configured AI provider enables fuller conversation.',
'source_mode':'Public source mode · use Search public sources to send a question to Wikipedia.','no_public_results':'No matching public sources. Try a shorter topic.',
'pet_help':'LAFA · click to chat · drag to move · right click for activities',
'virtual_settings':'Virtual Assistant','connections':'AI & language','files_weather':'Files & weather','bottom':'Bottom','top':'Top',
'api_ready':'API configured','api_missing':'API not configured','session_key':'New key · session only unless secure keyring is selected',
'model_hint':'Official model ID · Perplexity uses the fast preset','voice_note':'Tetun read-aloud uses Portuguese pronunciation. A native Tetun voice is not bundled.',
'wayland_note':'Automatic panel walking needs X11. Wayland allows manual placement controlled by the compositor.',
'key_external':'Environment keys are managed outside LAFA.','timezone':'Timezone · IANA / auto',
'you':'YOU','file_type':'Type','folder':'Folder','scanned':'scanned','source_title':'Source','summary':'Summary',
'public_library':'Wikipedia · public source search','compare_sources':'Read the source, compare facts, and ask LAFA for an explanation.',
'learning_library':'LEARNING LIBRARY','article_hint':'Wikipedia snippets; use Read for article introductions.',
'browser_login_note':'Sign in through your default browser. LAFA does not store website passwords or sessions.',
'headline':'Headline','publisher':'Publisher','published':'Published (UTC)','filter_headlines':'Filter headlines · optional','retrieved':'Retrieved','unavailable':'Unavailable',
'no_headlines':'No matching headlines.','headlines':'headlines','no_topic_news':'No matching topics in this feed window.',
'lesson_steps':'lesson steps','transcribe_question':'Record 8 seconds and send the audio to OpenAI for transcription?',
'voice_key':'Voice input requires an OpenAI API key. Add it in LAFA Settings.',
'review_banner':'REVIEW MODE · sample content · no API call','preview_only':'Review mode: no live requests.',
'review_chat':'Review mode is for visual inspection. Run LAFA normally to use public sources or configure an AI provider.',
'need_city':'Enter the home city name.','query_limit':'Use one public topic of at most 300 characters.',
},
'id':{
'public_search':'Cari sumber publik','public_hint':'Kirim pertanyaan ini ke Wikipedia. Gunakan topik publik; jangan sertakan informasi pribadi.',
'source_help':'Saya bisa membantu mencari sumber publik, membaca dokumen, melihat cuaca dan berita, serta latihan coding tanpa API key. Untuk pertanyaan publik, pilih Cari sumber publik atau /ask topik. Teks chat biasa tidak otomatis dikirim ke Wikipedia. Penyedia AI memungkinkan percakapan lebih lengkap.',
'source_mode':'Mode sumber publik · pilih Cari sumber publik untuk mengirim pertanyaan ke Wikipedia.','no_public_results':'Tidak ada sumber publik yang cocok. Coba topik lebih singkat.',
'pet_help':'LAFA · klik untuk berbicara · seret untuk memindahkan · klik kanan untuk aktivitas',
'virtual_settings':'Asisten Virtual','connections':'AI & bahasa','files_weather':'File & cuaca','bottom':'Bawah','top':'Atas',
'api_ready':'API dikonfigurasi','api_missing':'API belum dikonfigurasi','session_key':'Key baru · hanya sesi kecuali keyring aman dipilih',
'model_hint':'ID model resmi · Perplexity memakai preset fast','voice_note':'Baca bersuara Tetun memakai pelafalan Portugis. Suara Tetun asli belum disertakan.',
'wayland_note':'Berjalan otomatis di panel memerlukan X11. Wayland memakai penempatan manual oleh compositor.',
'key_external':'Key environment dikelola di luar LAFA.','timezone':'Zona waktu · IANA / auto',
'you':'ANDA','file_type':'Jenis','folder':'Folder','scanned':'dipindai','source_title':'Sumber','summary':'Ringkasan',
'public_library':'Wikipedia · pencarian sumber publik','compare_sources':'Baca sumber, bandingkan fakta, lalu minta penjelasan LAFA.',
'learning_library':'PUSTAKA BELAJAR','article_hint':'Cuplikan Wikipedia; pilih Baca untuk pengantar artikel.',
'browser_login_note':'Login melalui browser bawaan. LAFA tidak menyimpan kata sandi atau sesi situs.',
'headline':'Judul berita','publisher':'Penerbit','published':'Dipublikasikan (UTC)','filter_headlines':'Filter judul · opsional','retrieved':'Diambil','unavailable':'Tidak tersedia',
'no_headlines':'Tidak ada judul yang cocok.','headlines':'judul berita','no_topic_news':'Tidak ada topik yang cocok dalam feed ini.',
'lesson_steps':'langkah pelajaran','transcribe_question':'Rekam 8 detik dan kirim audio ke OpenAI untuk transkripsi?',
'voice_key':'Input suara memerlukan API key OpenAI. Tambahkan di Pengaturan LAFA.',
'review_banner':'MODE REVIEW · contoh konten · tanpa panggilan API','preview_only':'Mode review: tidak mengambil data langsung.',
'review_chat':'Mode review untuk meninjau tampilan. Jalankan LAFA normal untuk memakai sumber publik atau mengatur penyedia AI.',
'need_city':'Masukkan nama kota utama.','query_limit':'Gunakan satu topik publik maksimal 300 karakter.',
},
'pt':{
'public_search':'Pesquisar fontes públicas','public_hint':'Enviar a pergunta à Wikipedia. Use temas públicos; não inclua informação privada.',
'source_help':'Posso procurar fontes públicas, ler documentos, consultar tempo e notícias e praticar programação sem chave API. Para uma pergunta pública, use Pesquisar fontes públicas ou /ask tema. O texto normal da conversa não é enviado automaticamente à Wikipedia. Um fornecedor de IA permite uma conversa mais completa.',
'source_mode':'Modo de fontes públicas · use Pesquisar fontes públicas para enviar uma pergunta à Wikipedia.','no_public_results':'Nenhuma fonte pública corresponde. Tente um tema mais curto.',
'pet_help':'LAFA · clique para conversar · arraste para mover · botão direito para atividades',
'virtual_settings':'Assistente Virtual','connections':'IA e idioma','files_weather':'Ficheiros e tempo','bottom':'Inferior','top':'Superior',
'api_ready':'API configurada','api_missing':'API não configurada','session_key':'Nova chave · só nesta sessão, salvo porta-chaves seguro',
'model_hint':'ID oficial do modelo · Perplexity usa o preset fast','voice_note':'A leitura em Tetun usa pronúncia portuguesa. Não está incluída uma voz nativa de Tetun.',
'wayland_note':'Caminhar automaticamente no painel exige X11. Em Wayland a posição manual depende do compositor.',
'key_external':'As chaves de ambiente são geridas fora do LAFA.','timezone':'Fuso horário · IANA / auto',
'you':'VOCÊ','file_type':'Tipo','folder':'Pasta','scanned':'analisados','source_title':'Fonte','summary':'Resumo',
'public_library':'Wikipedia · pesquisa de fontes públicas','compare_sources':'Leia a fonte, compare os factos e peça uma explicação ao LAFA.',
'learning_library':'BIBLIOTECA DE APRENDIZAGEM','article_hint':'Excertos da Wikipedia; use Ler para introduções dos artigos.',
'browser_login_note':'Inicie sessão no navegador predefinido. LAFA não guarda palavras-passe nem sessões dos sites.',
'headline':'Título','publisher':'Editor','published':'Publicado (UTC)','filter_headlines':'Filtrar títulos · opcional','retrieved':'Obtido','unavailable':'Indisponível',
'no_headlines':'Nenhum título corresponde.','headlines':'títulos','no_topic_news':'Nenhum tema corresponde nesta janela do feed.',
'lesson_steps':'passos da lição','transcribe_question':'Gravar 8 segundos e enviar o áudio à OpenAI para transcrição?',
'voice_key':'A entrada de voz exige uma chave API OpenAI. Adicione-a nas Definições LAFA.',
'review_banner':'MODO DE REVISÃO · exemplos · sem chamada API','preview_only':'Modo de revisão: sem pedidos de dados em direto.',
'review_chat':'Modo de revisão para inspecionar a interface. Execute LAFA normalmente para usar fontes públicas ou configurar um fornecedor de IA.',
'need_city':'Introduza o nome da cidade principal.','query_limit':'Use um tema público até 300 caracteres.',
},
 'tet':{
'public_search':'Buka fonte públika','public_hint':'Haruka pergunta ba Wikipedia. Uza tópiku públiku; la inklui informasaun privada.',
'source_help':"Ha'u bele buka fonte públika, lee dokumentu, haree tempu no notísia no aprende kódigu sein xave API. Ba pergunta públika, uza Buka fonte públika ka /ask tópiku. Testu konversa normál la haruka automaticamente ba Wikipedia. Provedor IA permite konversa kompletu liu.",
'source_mode':'Modu fonte públika · uza Buka fonte públika atu haruka pergunta ba Wikipedia.','no_public_results':'La hetan fonte públika ne’ebé loos. Koko tópiku badak liu.',
'pet_help':'LAFA · klik atu ko’alia · dada atu muda fatin · klik direita ba atividade',
'virtual_settings':'Asistente Virtuál','connections':'IA no lian','files_weather':'Ficheiru no tempu','bottom':'Iha kraik','top':'Iha leten',
'api_ready':'API konfigura ona','api_missing':'API seidauk konfigura','session_key':'Xave foun · ba sesaun de’it ka keyring seguru',
'model_hint':'ID modelu ofisiál · Perplexity uza preset fast','voice_note':'Lee Tetun ho lian uza pronúnsia Portugés. Lian Tetun nativu seidauk inklui.',
'wayland_note':'La’o automaticamente iha painel presiza X11. Iha Wayland, compositor kontrola fatin manuál.',
'key_external':'Xave environment jere iha liur LAFA.','timezone':'Zona tempu · IANA / auto',
'you':'ITA','file_type':'Tipu','folder':'Pasta','scanned':'haree ona','source_title':'Fonte','summary':'Rezumu',
'public_library':'Wikipedia · buka fonte públika','compare_sources':'Lee fonte, kompara faktu no husu LAFA atu esplika.',
'learning_library':'BIBLIOTEKA APRENDIZAJEN','article_hint':'Rezumu Wikipedia; uza Lee ba introdusaun artigu.',
'browser_login_note':'Tama konta iha browser padraun. LAFA la rai senha ka sesaun sítiu.',
'headline':'Títulu notísia','publisher':'Publikadór','published':'Publika (UTC)','filter_headlines':'Filtra títulu · opsionál','retrieved':'Hetan','unavailable':'La disponivel',
'no_headlines':'La hetan títulu ne’ebé loos.','headlines':'títulu notísia','no_topic_news':'La hetan tópiku ne’ebé loos iha feed ne’e.',
'lesson_steps':'pasu lisaun','transcribe_question':'Grava segundu 8 no haruka áudio ba OpenAI atu halo transkrisaun?',
'voice_key':'Input lian presiza xave API OpenAI. Aumenta iha Konfigurasaun LAFA.',
'review_banner':'MODU REVIZAUN · ezemplu · sein chamada API','preview_only':'Modu revizaun: la husu dadus diretu.',
'review_chat':'Modu revizaun ba haree interface. Loke LAFA normál atu uza fonte públika ka konfigura provedor IA.',
'need_city':'Hakerek naran sidade prinsipál.','query_limit':'Uza tópiku públiku ida ho karakter to’o 300.',
}}

_RELEASE_EXTRAS={
'en':{'hub_chat_learning':'Chat & learning','hub_multimodal':'Chat & multimodal','hub_writing':'Writing & code','hub_chat_search':'Chat & search','hub_reasoning':'Chat & reasoning','hub_research':'Research & search','hub_notes':'Notes & sources','hub_images':'Images','hub_media':'Creative media','hub_voice':'Voice & audio','hub_code':'Coding','hub_apps':'Apps & websites','lesson_hello':'Hello, Timor-Leste','lesson_variables':'Variables and arithmetic','lesson_loops':'Loops','lesson_conditions':'Conditions','lesson_browser':'Browser basics','lesson_html':'My learning page','lesson_css':'Style a learning page'},
'id':{'hub_chat_learning':'Percakapan & belajar','hub_multimodal':'Percakapan & multimodal','hub_writing':'Menulis & kode','hub_chat_search':'Percakapan & pencarian','hub_reasoning':'Percakapan & penalaran','hub_research':'Riset & pencarian','hub_notes':'Catatan & sumber','hub_images':'Gambar','hub_media':'Media kreatif','hub_voice':'Suara & audio','hub_code':'Coding','hub_apps':'Aplikasi & situs','lesson_hello':'Halo, Timor-Leste','lesson_variables':'Variabel dan aritmetika','lesson_loops':'Perulangan','lesson_conditions':'Kondisi','lesson_browser':'Dasar browser','lesson_html':'Halaman belajar saya','lesson_css':'Gaya halaman belajar'},
'pt':{'hub_chat_learning':'Conversa e aprendizagem','hub_multimodal':'Conversa e multimodal','hub_writing':'Escrita e código','hub_chat_search':'Conversa e pesquisa','hub_reasoning':'Conversa e raciocínio','hub_research':'Investigação e pesquisa','hub_notes':'Notas e fontes','hub_images':'Imagens','hub_media':'Media criativos','hub_voice':'Voz e áudio','hub_code':'Programação','hub_apps':'Aplicações e sites','lesson_hello':'Olá, Timor-Leste','lesson_variables':'Variáveis e aritmética','lesson_loops':'Ciclos','lesson_conditions':'Condições','lesson_browser':'Noções do navegador','lesson_html':'A minha página de aprendizagem','lesson_css':'Estilo de uma página'},
 'tet':{'hub_chat_learning':'Konversa no aprendizajen','hub_multimodal':'Konversa no multimodál','hub_writing':'Hakerek no kódigu','hub_chat_search':'Konversa no peskiza','hub_reasoning':'Konversa no hanoin','hub_research':'Investigasaun no peskiza','hub_notes':'Nota no fonte','hub_images':'Imajen','hub_media':'Mídia kriativu','hub_voice':'Lian no áudio','hub_code':'Programasaun','hub_apps':'Aplikasaun no sítiu','lesson_hello':'Olá, Timor-Leste','lesson_variables':'Variavel no aritmétika','lesson_loops':'Repetisaun','lesson_conditions':'Kondisaun','lesson_browser':'Baze browser','lesson_html':'Ha’u-nia pájina aprendizajen','lesson_css':'Estilu pájina aprendizajen'},
}
for _language,_entries in _RELEASE_EXTRAS.items():RELEASE[_language].update(_entries)

# 0.1 Alpha restart: open-source providers, commands and Virtual Assistant greetings.
ALPHA={
'en':{'open_source_ready':'Open-source model · no paid API credits.','ollama_url':'Ollama address (this computer)','compatible_url':'Open-source server address (https://…/v1)','fetch_models':'Fetch available models','models_found':'models found. Choose one in the list.','greet_by_time':'Greet by time of day','open_source_note':'Open-source models: Ollama runs free on this computer (no key); an OpenAI-compatible open-source server can be hosted by a school or community. A key is optional for those servers.',
 'greet_morning':'Good morning!','greet_afternoon':'Good afternoon!','greet_evening':'Good evening!','calc':'Result',
 'help_text':'LAFA commands:\n/os topic — Edukasaun OS help\n/joke — a joke from LAFA\n/ask topic — public Wikipedia answer\n/learn topic — search encyclopedia sources\n/files name — find local files\n/web words — browser search link\n/weather city — weather and forecast\n/news words — world headlines\n/timor — Timor-Leste news\n/calc 3*(4+5) — calculator\n/remind 10 text — session reminder\n/focus — 25-minute focus timer\n/source Site: words — search a learning site\n/help — this list'},
'id':{'open_source_ready':'Model open-source · tanpa kredit API berbayar.','ollama_url':'Alamat Ollama (komputer ini)','compatible_url':'Alamat server open-source (https://…/v1)','fetch_models':'Ambil daftar model','models_found':'model ditemukan. Pilih dari daftar.','greet_by_time':'Sapa sesuai waktu','open_source_note':'Model open-source: Ollama berjalan gratis di komputer ini (tanpa key); server open-source kompatibel OpenAI dapat disediakan sekolah atau komunitas. Key opsional untuk server tersebut.',
 'greet_morning':'Selamat pagi!','greet_afternoon':'Selamat siang!','greet_evening':'Selamat malam!','calc':'Hasil',
 'help_text':'Perintah LAFA:\n/os topik — bantuan Edukasaun OS\n/joke — lelucon dari LAFA\n/ask topik — jawaban publik Wikipedia\n/learn topik — cari sumber ensiklopedia\n/files nama — cari file lokal\n/web kata — tautan pencarian browser\n/weather kota — cuaca dan prakiraan\n/news kata — berita dunia\n/timor — berita Timor-Leste\n/calc 3*(4+5) — kalkulator\n/remind 10 teks — pengingat sesi\n/focus — fokus 25 menit\n/source Situs: kata — cari di situs belajar\n/help — daftar ini'},
'pt':{'open_source_ready':'Modelo open-source · sem créditos de API pagos.','ollama_url':'Endereço do Ollama (este computador)','compatible_url':'Endereço do servidor open-source (https://…/v1)','fetch_models':'Obter modelos disponíveis','models_found':'modelos encontrados. Escolha um na lista.','greet_by_time':'Saudar conforme a hora','open_source_note':'Modelos open-source: o Ollama funciona gratuitamente neste computador (sem chave); um servidor open-source compatível com OpenAI pode ser alojado por uma escola ou comunidade. A chave é opcional.',
 'greet_morning':'Bom dia!','greet_afternoon':'Boa tarde!','greet_evening':'Boa noite!','calc':'Resultado',
 'help_text':'Comandos do LAFA:\n/os tema — ajuda do Edukasaun OS\n/joke — uma piada do LAFA\n/ask tema — resposta pública da Wikipédia\n/learn tema — procurar fontes\n/files nome — procurar ficheiros locais\n/web palavras — link de pesquisa\n/weather cidade — tempo e previsão\n/news palavras — notícias do mundo\n/timor — notícias de Timor-Leste\n/calc 3*(4+5) — calculadora\n/remind 10 texto — lembrete\n/focus — foco de 25 minutos\n/source Site: palavras — pesquisar num site\n/help — esta lista'},
'tet':{'open_source_ready':'Modelu open-source · la uza kréditu API selu.','ollama_url':'Enderesu Ollama (komputador ne’e)','compatible_url':'Enderesu servidór open-source (https://…/v1)','fetch_models':'Foti lista modelu','models_found':'modelu hetan. Hili ida iha lista.','greet_by_time':'Kumprimenta tuir oras','open_source_note':'Modelu open-source: Ollama la’o grátis iha komputador ne’e (sein xave); servidór open-source kompatível OpenAI bele hosti husi eskola ka komunidade. Xave opsionál.',
 'greet_morning':'Bondia!','greet_afternoon':'Boatarde!','greet_evening':'Boanoite!','calc':'Rezultadu',
 'help_text':'Komandu LAFA:\n/os tópiku — ajuda Edukasaun OS\n/joke — anedota husi LAFA\n/ask tópiku — resposta públika Wikipédia\n/learn tópiku — buka fonte\n/files naran — buka ficheiru lokál\n/web liafuan — ligasaun buka\n/weather sidade — tempu no previzaun\n/news liafuan — notísia mundu\n/timor — notísia Timor-Leste\n/calc 3*(4+5) — kalkuladora\n/remind 10 testu — lembransa\n/focus — foku minutu 25\n/source Sítiu: liafuan — buka iha sítiu\n/help — lista ne’e'},
}

# 0.1 Alpha redesign: Home dashboard, Edukasaun OS help, personality settings.
REDESIGN={
'en':{'home':'Home','home_sub':'Your learning companion and Edukasaun OS helper','os_help':'Edukasaun OS help','os_short':'OS help','tell_joke':'Tell me a joke',
 'virtual_on':'LAFA Virtual Assistant is active on the Eduka-Panel.','virtual_off':'LAFA Virtual Assistant is off. Turn it on to have LAFA walk on your Eduka-Panel.','turn_on':'Turn on Virtual Assistant','turn_off':'Turn off',
 'can_do':'What LAFA can do for you','card_os_d':'Step-by-step help: Wi-Fi, sound, files, apps, updates, printer…','card_chat_d':'Ask questions, public sources, /calc, jokes and reminders','card_files_d':'Find and read documents, music, videos and pictures','card_learn_d':'Wikipedia, OpenStax, Khan Academy and more','card_coding_d':'Practise Python; read HTML, CSS and JavaScript','card_live_d':'Weather forecast and world headlines','card_reminders_d':'Focus timer and session reminders','card_culture_d':'Timor-Leste news, culture and Tebe dance','card_hub_d':'Open ChatGPT, Gemini, Claude and more in the browser',
 'tip_title':'Tip of the day','syscheck':'System check','refresh_check':'Check again','sys_os':'System','sys_desktop':'Desktop · session','sys_disk':'Free disk','sys_memory':'Free memory','sys_battery':'Battery',
 'open_tool':'Open tool','tool_missing':'This tool is not installed on this computer. Follow the steps, or ask your teacher or administrator.','os_intro':'Choose a topic, or ask LAFA in chat, for example “how do I connect Wi-Fi?”. LAFA only opens desktop tools; it never changes system settings by itself.','os_topics':'Topics','os_list':'Edukasaun OS help topics (type /os topic):',
 'settings_in_eduka':'Settings · Eduka-Settings','personality_settings':'Personality & activities','hover_questions':'Ask “Can I help?” when the cursor touches LAFA','chatter':'LAFA talks about what it is doing','fun_messages':'Jokes and fun messages between cards','activity_seconds':'Change activity after (seconds)','about':'About',
 'about_text':'LAFA is an open-source virtual assistant for Edukasaun OS. It has no main server: it uses the internet, public open sources and optional AI providers you choose. Settings are stored in ~/.config/lafa; API keys stay in memory or the secure keyring.',
 'chip_1':'How do I connect Wi-Fi?','chip_2':'/weather','chip_3':'/calc 12*7','chip_4':'Tell me a joke','chat_welcome':'Ask me anything, or tap a suggestion below.','eduka_settings_note':'All LAFA preferences are also available in Eduka-Settings → LAFA.'},
'id':{'home':'Beranda','home_sub':'Teman belajar dan pemandu Edukasaun OS','os_help':'Bantuan Edukasaun OS','os_short':'Bantuan OS','tell_joke':'Ceritakan lelucon',
 'virtual_on':'LAFA Asisten Virtual aktif di Eduka-Panel.','virtual_off':'LAFA Asisten Virtual mati. Aktifkan agar LAFA berjalan di Eduka-Panel.','turn_on':'Aktifkan Asisten Virtual','turn_off':'Matikan',
 'can_do':'Yang bisa LAFA bantu','card_os_d':'Panduan langkah demi langkah: Wi-Fi, suara, file, aplikasi, pembaruan, printer…','card_chat_d':'Tanya jawab, sumber publik, /calc, lelucon dan pengingat','card_files_d':'Cari dan baca dokumen, musik, video dan gambar','card_learn_d':'Wikipedia, OpenStax, Khan Academy dan lainnya','card_coding_d':'Latihan Python; baca HTML, CSS dan JavaScript','card_live_d':'Prakiraan cuaca dan berita dunia','card_reminders_d':'Timer fokus dan pengingat','card_culture_d':'Berita, budaya dan tarian Tebe Timor-Leste','card_hub_d':'Buka ChatGPT, Gemini, Claude dan lainnya di browser',
 'tip_title':'Tips hari ini','syscheck':'Cek sistem','refresh_check':'Cek lagi','sys_os':'Sistem','sys_desktop':'Desktop · sesi','sys_disk':'Disk kosong','sys_memory':'Memori kosong','sys_battery':'Baterai',
 'open_tool':'Buka alat','tool_missing':'Alat ini belum terpasang di komputer ini. Ikuti langkahnya, atau tanya guru atau administrator.','os_intro':'Pilih topik, atau tanya LAFA di percakapan, misalnya “cara sambung Wi-Fi?”. LAFA hanya membuka alat desktop; tidak pernah mengubah pengaturan sistem sendiri.','os_topics':'Topik','os_list':'Topik bantuan Edukasaun OS (ketik /os topik):',
 'settings_in_eduka':'Pengaturan · Eduka-Settings','personality_settings':'Kepribadian & aktivitas','hover_questions':'Tanya “Bisa saya bantu?” saat kursor menyentuh LAFA','chatter':'LAFA bercerita tentang kegiatannya','fun_messages':'Lelucon dan pesan lucu di antara kartu','activity_seconds':'Ganti aktivitas setelah (detik)','about':'Tentang',
 'about_text':'LAFA adalah asisten virtual open-source untuk Edukasaun OS. Tanpa server utama: memakai internet, sumber terbuka publik, dan penyedia AI pilihanmu. Pengaturan disimpan di ~/.config/lafa; API key hanya di memori atau keyring aman.',
 'chip_1':'Cara sambung Wi-Fi?','chip_2':'/weather','chip_3':'/calc 12*7','chip_4':'Ceritakan lelucon','chat_welcome':'Tanyakan apa saja, atau pilih saran di bawah.','eduka_settings_note':'Semua pengaturan LAFA juga ada di Eduka-Settings → LAFA.'},
'pt':{'home':'Início','home_sub':'Companheiro de aprendizagem e guia do Edukasaun OS','os_help':'Ajuda do Edukasaun OS','os_short':'Ajuda SO','tell_joke':'Conta uma piada',
 'virtual_on':'O Assistente Virtual LAFA está ativo no Eduka-Panel.','virtual_off':'O Assistente Virtual está desligado. Ligue-o para o LAFA passear no Eduka-Panel.','turn_on':'Ligar Assistente Virtual','turn_off':'Desligar',
 'can_do':'O que o LAFA pode fazer','card_os_d':'Ajuda passo a passo: Wi-Fi, som, ficheiros, aplicações, atualizações, impressora…','card_chat_d':'Perguntas, fontes públicas, /calc, piadas e lembretes','card_files_d':'Procurar e ler documentos, música, vídeos e imagens','card_learn_d':'Wikipédia, OpenStax, Khan Academy e mais','card_coding_d':'Praticar Python; ler HTML, CSS e JavaScript','card_live_d':'Previsão do tempo e notícias do mundo','card_reminders_d':'Temporizador de foco e lembretes','card_culture_d':'Notícias, cultura e dança Tebe de Timor-Leste','card_hub_d':'Abrir ChatGPT, Gemini, Claude e outros no navegador',
 'tip_title':'Dica do dia','syscheck':'Verificação do sistema','refresh_check':'Verificar de novo','sys_os':'Sistema','sys_desktop':'Ambiente · sessão','sys_disk':'Disco livre','sys_memory':'Memória livre','sys_battery':'Bateria',
 'open_tool':'Abrir ferramenta','tool_missing':'Esta ferramenta não está instalada. Siga os passos ou pergunte ao professor ou administrador.','os_intro':'Escolha um tema ou pergunte ao LAFA, por exemplo “como ligar o Wi-Fi?”. O LAFA só abre ferramentas; nunca altera o sistema sozinho.','os_topics':'Temas','os_list':'Temas de ajuda do Edukasaun OS (escreva /os tema):',
 'settings_in_eduka':'Definições · Eduka-Settings','personality_settings':'Personalidade e atividades','hover_questions':'Perguntar “Posso ajudar?” quando o cursor toca no LAFA','chatter':'O LAFA comenta o que está a fazer','fun_messages':'Piadas e mensagens divertidas','activity_seconds':'Mudar de atividade após (segundos)','about':'Sobre',
 'about_text':'O LAFA é um assistente virtual open-source para o Edukasaun OS. Não tem servidor principal: usa a internet, fontes abertas públicas e fornecedores de IA à sua escolha. Definições em ~/.config/lafa; chaves API só em memória ou no porta-chaves seguro.',
 'chip_1':'Como ligar o Wi-Fi?','chip_2':'/weather','chip_3':'/calc 12*7','chip_4':'Conta uma piada','chat_welcome':'Pergunte o que quiser ou escolha uma sugestão.','eduka_settings_note':'Todas as preferências do LAFA também estão em Eduka-Settings → LAFA.'},
'tet':{'home':'Uma','home_sub':'Ita-nia belun aprendizajen no matadalan Edukasaun OS','os_help':'Ajuda Edukasaun OS','os_short':'Ajuda OS','tell_joke':'Konta anedota ida',
 'virtual_on':'LAFA Asistente Virtuál ativu iha Eduka-Panel.','virtual_off':'LAFA Asistente Virtuál mate. Ativa atu LAFA la’o iha Eduka-Panel.','turn_on':'Ativa Asistente Virtuál','turn_off':'Hamate',
 'can_do':'Buat ne’ebé LAFA bele halo','card_os_d':'Ajuda pasu ba pasu: Wi-Fi, lian, ficheiru, aplikasaun, atualizasaun, impresora…','card_chat_d':'Husu, fonte públika, /calc, anedota no lembransa','card_files_d':'Buka no lee dokumentu, múzika, vídeu no imajen','card_learn_d':'Wikipédia, OpenStax, Khan Academy no seluk','card_coding_d':'Pratika Python; lee HTML, CSS no JavaScript','card_live_d':'Previzaun tempu no notísia mundu','card_reminders_d':'Timer foku no lembransa','card_culture_d':'Notísia, kultura no dansa Tebe Timor-Leste','card_hub_d':'Loke ChatGPT, Gemini, Claude no seluk iha browser',
 'tip_title':'Dika ohin nian','syscheck':'Verifika sistema','refresh_check':'Verifika fali','sys_os':'Sistema','sys_desktop':'Desktop · sesaun','sys_disk':'Disku mamuk','sys_memory':'Memória mamuk','sys_battery':'Bateria',
 'open_tool':'Loke ferramenta','tool_missing':'Ferramenta ne’e seidauk instala. Tuir pasu sira, ka husu ba mestre ka administradór.','os_intro':'Hili tópiku ida, ka husu LAFA iha konversa, ezemplu “oinsá liga Wi-Fi?”. LAFA loke de’it ferramenta; nunka troka sistema mesak.','os_topics':'Tópiku','os_list':'Tópiku ajuda Edukasaun OS (hakerek /os tópiku):',
 'settings_in_eduka':'Konfigurasaun · Eduka-Settings','personality_settings':'Karakter no atividade','hover_questions':'Husu “Ha’u bele ajuda?” bainhira kursór kona LAFA','chatter':'LAFA koalia kona-ba ninia atividade','fun_messages':'Anedota no mensajen kmanek','activity_seconds':'Troka atividade depois (segundu)','about':'Kona-ba',
 'about_text':'LAFA mak asistente virtuál open-source ba Edukasaun OS. La iha servidór prinsipál: uza internet, fonte públika aberta no provedor IA ne’ebé ita hili. Konfigurasaun rai iha ~/.config/lafa; xave API iha memória ka keyring seguru de’it.',
 'chip_1':'Oinsá liga Wi-Fi?','chip_2':'/weather','chip_3':'/calc 12*7','chip_4':'Konta anedota ida','chat_welcome':'Husu saida de’it, ka hili sujestaun iha okos.','eduka_settings_note':'Konfigurasaun LAFA hotu mós iha Eduka-Settings → LAFA.'},
}

# 0.1.1: LAFA School (teachers, homework, timetable) and school navigation.
SCHOOL={
'en':{'teachers':'Teachers','homework':'Homework & timetable','library':'Library','lab':'Computer lab','noticeboard':'Notice board','helpdesk':'IT help desk',
 'ask_teacher':'Ask the teacher','practice':'Practice','new_question':'New question','check':'Check','correct':'Correct! Great job! 🎉','try_again':'Not quite — try again! Answer:','resources':'Free learning resources','level':'Level',
 'teacher_needs_ai':'Teachers explain step by step with an AI provider (free open-source Ollama works). Without AI, use the practice, the resources and “Search public sources”.',
 'homework_title':'What is the homework?','subject':'Subject','due':'Due date','add_homework':'Add homework','done':'Done','delete':'Delete','to_agenda':'Also add to the Eduka-Panel calendar','timetable':'Timetable',
 'days':'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday','period':'Period','today_school':'Today at school','no_classes':'No classes in the timetable for today.','homework_due':'Homework due soon','no_homework':'No homework pending. Well done!',
 'other':'Other','translate_from':'From','translate_to':'To','card_teachers_d':'A teacher for every subject, free resources and practice','card_homework_d':'Homework planner, timetable and calendar','school_sub':'LAFA School',
 'counsellor_tip':'Tip from the counsellor','next_tip':'Another tip','score':'Score','saved_agenda':'Added to the Eduka-Panel calendar.','reminders_short':'Reminders & focus','sources_updated':'LAFA updated its learning sources.','release_available':'A new LAFA version is available: {version}. Update it with the Eduka Update System or your software centre.'},
'id':{'teachers':'Guru','homework':'PR & jadwal','library':'Perpustakaan','lab':'Lab komputer','noticeboard':'Papan pengumuman','helpdesk':'Meja bantuan TI',
 'ask_teacher':'Tanya guru','practice':'Latihan','new_question':'Soal baru','check':'Periksa','correct':'Benar! Hebat! 🎉','try_again':'Belum tepat — coba lagi! Jawaban:','resources':'Sumber belajar gratis','level':'Tingkat',
 'teacher_needs_ai':'Guru menjelaskan langkah demi langkah dengan penyedia AI (Ollama open-source gratis bisa). Tanpa AI, pakai latihan, sumber belajar dan “Cari sumber publik”.',
 'homework_title':'Apa PR-nya?','subject':'Mata pelajaran','due':'Batas waktu','add_homework':'Tambah PR','done':'Selesai','delete':'Hapus','to_agenda':'Tambahkan juga ke kalender Eduka-Panel','timetable':'Jadwal pelajaran',
 'days':'Senin,Selasa,Rabu,Kamis,Jumat,Sabtu','period':'Jam ke','today_school':'Hari ini di sekolah','no_classes':'Tidak ada pelajaran di jadwal hari ini.','homework_due':'PR yang segera dikumpulkan','no_homework':'Tidak ada PR. Hebat!',
 'other':'Lainnya','translate_from':'Dari','translate_to':'Ke','card_teachers_d':'Guru untuk setiap pelajaran, sumber gratis dan latihan','card_homework_d':'Perencana PR, jadwal dan kalender','school_sub':'Sekolah LAFA',
 'counsellor_tip':'Tips dari guru BK','next_tip':'Tips lain','score':'Skor','saved_agenda':'Ditambahkan ke kalender Eduka-Panel.','reminders_short':'Pengingat & fokus','sources_updated':'LAFA memperbarui sumber belajarnya.','release_available':'Versi LAFA baru tersedia: {version}. Perbarui lewat Eduka Update System atau pusat perangkat lunak.'},
'pt':{'teachers':'Professores','homework':'Trabalhos e horário','library':'Biblioteca','lab':'Sala de informática','noticeboard':'Quadro de avisos','helpdesk':'Apoio informático',
 'ask_teacher':'Perguntar ao professor','practice':'Prática','new_question':'Nova pergunta','check':'Verificar','correct':'Certo! Muito bem! 🎉','try_again':'Ainda não — tenta outra vez! Resposta:','resources':'Recursos gratuitos','level':'Nível',
 'teacher_needs_ai':'Os professores explicam passo a passo com um fornecedor de IA (o Ollama open-source gratuito serve). Sem IA, usa a prática, os recursos e “Pesquisar fontes públicas”.',
 'homework_title':'Qual é o trabalho de casa?','subject':'Disciplina','due':'Data de entrega','add_homework':'Adicionar trabalho','done':'Feito','delete':'Apagar','to_agenda':'Adicionar também ao calendário do Eduka-Panel','timetable':'Horário',
 'days':'Segunda,Terça,Quarta,Quinta,Sexta,Sábado','period':'Tempo','today_school':'Hoje na escola','no_classes':'Sem aulas no horário de hoje.','homework_due':'Trabalhos para breve','no_homework':'Sem trabalhos pendentes. Muito bem!',
 'other':'Outro','translate_from':'De','translate_to':'Para','card_teachers_d':'Um professor para cada disciplina, recursos e prática','card_homework_d':'Planeador de trabalhos, horário e calendário','school_sub':'Escola LAFA',
 'counsellor_tip':'Dica do orientador','next_tip':'Outra dica','score':'Pontos','saved_agenda':'Adicionado ao calendário do Eduka-Panel.','reminders_short':'Lembretes e foco','sources_updated':'O LAFA atualizou as fontes de aprendizagem.','release_available':'Nova versão do LAFA disponível: {version}. Atualize com o Eduka Update System ou o centro de software.'},
'tet':{'teachers':'Mestre sira','homework':'TPC no orariu','library':'Biblioteka','lab':'Lab komputadór','noticeboard':'Kuadru avizu','helpdesk':'Ajuda TI',
 'ask_teacher':'Husu mestre','practice':'Pratika','new_question':'Pergunta foun','check':'Verifika','correct':'Loos! Di’ak tebes! 🎉','try_again':'Seidauk loos — koko fali! Resposta:','resources':'Fonte aprende grátis','level':'Nivel',
 'teacher_needs_ai':'Mestre esplika pasu ba pasu ho provedor IA (Ollama open-source grátis bele). Sein IA, uza pratika, fonte sira no “Buka fonte públika”.',
 'homework_title':'TPC mak saida?','subject':'Matéria','due':'Data entrega','add_homework':'Aumenta TPC','done':'Remata','delete':'Hamoos','to_agenda':'Aumenta mós ba kalendáriu Eduka-Panel','timetable':'Orariu',
 'days':'Segunda,Tersa,Kuarta,Kinta,Sesta,Sábadu','period':'Oras','today_school':'Ohin iha eskola','no_classes':'La iha lisaun iha orariu ohin.','homework_due':'TPC atu entrega lalais','no_homework':'La iha TPC. Di’ak tebes!',
 'other':'Seluk','translate_from':'Husi','translate_to':'Ba','card_teachers_d':'Mestre ba matéria ida-idak, fonte grátis no pratika','card_homework_d':'Planeadór TPC, orariu no kalendáriu','school_sub':'Eskola LAFA',
 'counsellor_tip':'Dika husi konselleiru','next_tip':'Dika seluk','score':'Pontu','saved_agenda':'Aumenta ona ba kalendáriu Eduka-Panel.','reminders_short':'Lembransa no foku','sources_updated':'LAFA atualiza ona ninia fonte aprende.','release_available':'Versaun LAFA foun iha: {version}. Atualiza ho Eduka Update System ka sentru software.'},
}

# Lafa-Configuration options shared by LAFA's own settings window.
CONFIG={
'en':{'character_size':'Character size','walk_speed':'Walking speed','animation_speed':'Animation speed','follow_eduka_panel':'Follow Eduka-Panel position and size','start_with_session':'Start with Eduka-Desktop when activated',
 'balloon_seconds':'Speech balloon time (seconds)','start_page':'Start page','follow_eduka_theme':'Use the Eduka-Desktop theme and accent colour','notifications':'Reminders as Eduka-Panel notifications',
 'auto_update':'Keep learning sources up to date automatically','update_hours':'Check for updates every (hours)','speech_rate':'Reading speed (words/min)','desktop_settings':'LAFA Desktop',
 'slow':'Slow','normal':'Normal','fast':'Fast','small':'Small','large':'Large'},
'id':{'character_size':'Ukuran karakter','walk_speed':'Kecepatan berjalan','animation_speed':'Kecepatan animasi','follow_eduka_panel':'Ikuti posisi dan ukuran Eduka-Panel','start_with_session':'Mulai bersama Eduka-Desktop saat aktif',
 'balloon_seconds':'Lama balon bicara (detik)','start_page':'Halaman awal','follow_eduka_theme':'Pakai tema dan warna aksen Eduka-Desktop','notifications':'Pengingat sebagai notifikasi Eduka-Panel',
 'auto_update':'Perbarui sumber belajar otomatis','update_hours':'Periksa pembaruan setiap (jam)','speech_rate':'Kecepatan membaca (kata/menit)','desktop_settings':'LAFA Desktop',
 'slow':'Pelan','normal':'Normal','fast':'Cepat','small':'Kecil','large':'Besar'},
'pt':{'character_size':'Tamanho da personagem','walk_speed':'Velocidade a caminhar','animation_speed':'Velocidade da animação','follow_eduka_panel':'Seguir a posição do Eduka-Panel','start_with_session':'Iniciar com o Eduka-Desktop',
 'balloon_seconds':'Tempo do balão (segundos)','start_page':'Página inicial','follow_eduka_theme':'Usar o tema e a cor do Eduka-Desktop','notifications':'Lembretes como notificações do Eduka-Panel',
 'auto_update':'Atualizar as fontes automaticamente','update_hours':'Verificar atualizações a cada (horas)','speech_rate':'Velocidade de leitura','desktop_settings':'LAFA Desktop',
 'slow':'Lento','normal':'Normal','fast':'Rápido','small':'Pequeno','large':'Grande'},
'tet':{'character_size':'Tamañu karakter','walk_speed':'Velosidade la’o','animation_speed':'Velosidade animasaun','follow_eduka_panel':'Tuir pozisaun Eduka-Panel','start_with_session':'Hahú ho Eduka-Desktop',
 'balloon_seconds':'Tempu balaun (segundu)','start_page':'Pájina inisiál','follow_eduka_theme':'Uza tema no kór Eduka-Desktop','notifications':'Lembransa hanesan notifikasaun Eduka-Panel',
 'auto_update':'Atualiza fonte aprende automátiku','update_hours':'Verifika atualizasaun kada (oras)','speech_rate':'Velosidade lee','desktop_settings':'LAFA Desktop',
 'slow':'Neineik','normal':'Normál','fast':'Lalais','small':'Ki’ik','large':'Boot'},
}

# LAFA 0.1.2: classroom, exam hall, report card, Timor-Leste and roles.
CLASS={
'en':{'card_culture_d':'History, symbols, places and news of Timor-Leste','classroom':'Classroom','exams':'Exam hall','report_card':'Report card','sec_school':'SCHOOL','sec_timor':'TIMOR-LESTE','sec_resources':'LIBRARY & LABS','sec_help':'HELP & TOOLS',
 'lessons':'Lessons','lesson_task':'Try it','quiz':'Quiz','test':'Test','exam':'Exam','all_subjects':'All subjects','start_exam':'Start','question_n':'Question {n} of {total}','time_left':'Time left','finish':'Finish',
 'result':'Result','grade':'Grade','mistakes':'Check your mistakes','correct_answer':'Correct answer','average':'Average','best':'Best','attempts':'Attempts','history_label':'History','export_report':'Export…','saved_to':'Saved to','no_results':'No results yet — take a quiz in the Exam hall!',
 'word_of_day':'Word of the day','motivation_of_day':'LAFA says','today_in_history':'Today in Timor-Leste','next_holiday':'Next holiday: {name} in {days} days ({date})','holiday_today':'Today is a public holiday: {name}',
 'roles':"LAFA's roles",'roles_sub':'One friend, many hats: choose who LAFA should be right now.','mind_reader':'Mind reader','mind_intro':'Think of a number from 1 to 63. Tell me on which cards you can see it — I will read your mind!','mind_question':'Card {n} of 6 — is your number here?','yes':'Yes','no':'No','mind_result':'🎩 Your number is {n}! The secret: each card is a binary digit (1, 2, 4, 8, 16, 32).',
 'history_tab':'History','nation_tab':'Nation & symbols','news_tab':'News & culture','municipalities':'Municipalities','main_town':'Main town','holidays':'Public holidays','read_more':'Read more','test_yourself':'Test yourself',
 'practice_subject':'Quiz on this subject','open_teacher':'Ask the teacher','card_classroom_d':'Lessons and study notes for every subject','card_exams_d':'Quizzes, tests and exams with instant results','card_report_d':'Your scores, grades and progress',
 'quiz_d':'5 questions · instant feedback · practice','test_d':'10 questions on one subject · results at the end','exam_d':'20 questions from all subjects · 20 minutes','date':'Date','kind':'Type','start_hint':'Choose a type and a subject, then press Start.',
 'exam_done':'Finished! {score}/{total} correct ({percent}%) · {grade}','saved_report':'Saved in your report card.','event':'Event','era':'Era','timor_sub':'From the first people to today: history, symbols, places and news of Timor-Leste.'},
'id':{'card_culture_d':'Sejarah, simbol, tempat dan berita Timor-Leste','classroom':'Ruang kelas','exams':'Ruang ujian','report_card':'Rapor','sec_school':'SEKOLAH','sec_timor':'TIMOR-LESTE','sec_resources':'PERPUSTAKAAN & LAB','sec_help':'BANTUAN & ALAT',
 'lessons':'Pelajaran','lesson_task':'Coba ini','quiz':'Kuis','test':'Ulangan','exam':'Ujian','all_subjects':'Semua mata pelajaran','start_exam':'Mulai','question_n':'Soal {n} dari {total}','time_left':'Sisa waktu','finish':'Selesai',
 'result':'Hasil','grade':'Nilai','mistakes':'Periksa kesalahanmu','correct_answer':'Jawaban benar','average':'Rata-rata','best':'Terbaik','attempts':'Percobaan','history_label':'Riwayat','export_report':'Ekspor…','saved_to':'Disimpan ke','no_results':'Belum ada hasil — coba kuis di Ruang ujian!',
 'word_of_day':'Kata hari ini','motivation_of_day':'Kata LAFA','today_in_history':'Hari ini di Timor-Leste','next_holiday':'Hari libur berikutnya: {name} dalam {days} hari ({date})','holiday_today':'Hari ini libur nasional: {name}',
 'roles':'Peran LAFA','roles_sub':'Satu teman, banyak peran: pilih LAFA mau jadi apa sekarang.','mind_reader':'Pembaca pikiran','mind_intro':'Pikirkan angka 1 sampai 63. Katakan di kartu mana angkamu ada — saya akan membaca pikiranmu!','mind_question':'Kartu {n} dari 6 — apakah angkamu di sini?','yes':'Ya','no':'Tidak','mind_result':'🎩 Angkamu {n}! Rahasianya: setiap kartu adalah digit biner (1, 2, 4, 8, 16, 32).',
 'history_tab':'Sejarah','nation_tab':'Negara & simbol','news_tab':'Berita & budaya','municipalities':'Munisipalitas','main_town':'Kota utama','holidays':'Hari libur nasional','read_more':'Baca lebih lanjut','test_yourself':'Uji dirimu',
 'practice_subject':'Kuis mata pelajaran ini','open_teacher':'Tanya guru','card_classroom_d':'Pelajaran dan catatan untuk setiap mata pelajaran','card_exams_d':'Kuis, ulangan dan ujian dengan hasil langsung','card_report_d':'Skor, nilai dan kemajuanmu',
 'quiz_d':'5 soal · umpan balik langsung · latihan','test_d':'10 soal satu mata pelajaran · hasil di akhir','exam_d':'20 soal semua mata pelajaran · 20 menit','date':'Tanggal','kind':'Jenis','start_hint':'Pilih jenis dan mata pelajaran, lalu tekan Mulai.',
 'exam_done':'Selesai! {score}/{total} benar ({percent}%) · {grade}','saved_report':'Tersimpan di rapor.','event':'Peristiwa','era':'Era','timor_sub':'Dari manusia pertama sampai hari ini: sejarah, simbol, tempat dan berita Timor-Leste.'},
'pt':{'card_culture_d':'História, símbolos, lugares e notícias de Timor-Leste','classroom':'Sala de aula','exams':'Sala de exames','report_card':'Boletim','sec_school':'ESCOLA','sec_timor':'TIMOR-LESTE','sec_resources':'BIBLIOTECA E LABORATÓRIOS','sec_help':'AJUDA E FERRAMENTAS',
 'lessons':'Aulas','lesson_task':'Experimenta','quiz':'Quiz','test':'Teste','exam':'Exame','all_subjects':'Todas as disciplinas','start_exam':'Começar','question_n':'Pergunta {n} de {total}','time_left':'Tempo restante','finish':'Terminar',
 'result':'Resultado','grade':'Classificação','mistakes':'Revê os teus erros','correct_answer':'Resposta certa','average':'Média','best':'Melhor','attempts':'Tentativas','history_label':'Histórico','export_report':'Exportar…','saved_to':'Guardado em','no_results':'Ainda sem resultados — faz um quiz na Sala de exames!',
 'word_of_day':'Palavra do dia','motivation_of_day':'O LAFA diz','today_in_history':'Hoje em Timor-Leste','next_holiday':'Próximo feriado: {name} daqui a {days} dias ({date})','holiday_today':'Hoje é feriado: {name}',
 'roles':'Papéis do LAFA','roles_sub':'Um amigo, muitos chapéus: escolhe quem o LAFA deve ser agora.','mind_reader':'Leitor de mentes','mind_intro':'Pensa num número de 1 a 63. Diz-me em que cartas o vês — vou ler a tua mente!','mind_question':'Carta {n} de 6 — o teu número está aqui?','yes':'Sim','no':'Não','mind_result':'🎩 O teu número é {n}! O segredo: cada carta é um algarismo binário (1, 2, 4, 8, 16, 32).',
 'history_tab':'História','nation_tab':'Nação e símbolos','news_tab':'Notícias e cultura','municipalities':'Municípios','main_town':'Sede','holidays':'Feriados','read_more':'Ler mais','test_yourself':'Testa-te',
 'practice_subject':'Quiz desta disciplina','open_teacher':'Perguntar ao professor','card_classroom_d':'Aulas e apontamentos de todas as disciplinas','card_exams_d':'Quizzes, testes e exames com resultados imediatos','card_report_d':'As tuas notas e progresso',
 'quiz_d':'5 perguntas · correção imediata · prática','test_d':'10 perguntas de uma disciplina · resultado no fim','exam_d':'20 perguntas de todas as disciplinas · 20 minutos','date':'Data','kind':'Tipo','start_hint':'Escolhe o tipo e a disciplina e carrega em Começar.',
 'exam_done':'Terminado! {score}/{total} certas ({percent}%) · {grade}','saved_report':'Guardado no boletim.','event':'Acontecimento','era':'Época','timor_sub':'Dos primeiros povos até hoje: história, símbolos, lugares e notícias de Timor-Leste.'},
'tet':{'card_culture_d':'Istória, símbolu, fatin no notísia Timor-Leste','classroom':'Sala aula','exams':'Sala ezame','report_card':'Boletin','sec_school':'ESKOLA','sec_timor':'TIMOR-LESTE','sec_resources':'BIBLIOTEKA NO LABORATÓRIU','sec_help':'AJUDA NO FERRAMENTA',
 'lessons':'Lisaun','lesson_task':'Koko halo','quiz':'Kuis','test':'Teste','exam':'Ezame','all_subjects':'Matéria hotu','start_exam':'Hahú','question_n':'Pergunta {n} husi {total}','time_left':'Tempu sobra','finish':'Remata',
 'result':'Rezultadu','grade':'Valór','mistakes':'Haree ita-nia sala','correct_answer':'Resposta loos','average':'Média','best':'Di\'ak liu','attempts':'Koko','history_label':'Istóriku','export_report':'Esporta…','saved_to':'Rai iha','no_results':'Seidauk iha rezultadu — koko kuis iha Sala ezame!',
 'word_of_day':'Liafuan ohin nian','motivation_of_day':'LAFA dehan','today_in_history':'Ohin iha Timor-Leste','next_holiday':'Feriadu tuir mai: {name} iha loron {days} ({date})','holiday_today':'Ohin feriadu: {name}',
 'roles':'Papél LAFA','roles_sub':'Belun ida, papél barak: hili LAFA tenke sai saida agora.','mind_reader':'Lee hanoin','mind_intro':'Hanoin númeru ida husi 1 to\'o 63. Hatete ba ha\'u iha karta ne\'ebé ita haree — ha\'u sei lee ita-nia hanoin!','mind_question':'Karta {n} husi 6 — ita-nia númeru iha ne\'e?','yes':'Sin','no':'Lae','mind_result':'🎩 Ita-nia númeru mak {n}! Segredu: karta ida-idak mak dijitu bináriu (1, 2, 4, 8, 16, 32).',
 'history_tab':'Istória','nation_tab':'Nasaun no símbolu','news_tab':'Notísia no kultura','municipalities':'Munisípiu','main_town':'Sidade prinsipál','holidays':'Feriadu nasionál','read_more':'Lee tan','test_yourself':'Teste an',
 'practice_subject':'Kuis ba matéria ne\'e','open_teacher':'Husu mestre','card_classroom_d':'Lisaun no nota ba matéria hotu','card_exams_d':'Kuis, teste no ezame ho rezultadu kedas','card_report_d':'Ita-nia pontu, valór no progresu',
 'quiz_d':'Pergunta 5 · korresaun kedas · pratika','test_d':'Pergunta 10 kona-ba matéria ida · rezultadu iha ikus','exam_d':'Pergunta 20 husi matéria hotu · minutu 20','date':'Data','kind':'Tipu','start_hint':'Hili tipu no matéria, depois klik Hahú.',
 'exam_done':'Remata! {score}/{total} loos ({percent}%) · {grade}','saved_report':'Rai ona iha boletin.','event':'Akontesimentu','era':'Era','timor_sub':'Husi ema dahuluk to\'o ohin: istória, símbolu, fatin no notísia Timor-Leste.'},
}

CATALOG={code:{**dict(zip(KEYS,strings)),**EXTRA[code],**NEW[code],**RELEASE[code],**ALPHA[code],**REDESIGN[code],**SCHOOL[code],**CONFIG[code],**CLASS[code]} for code,strings in STRINGS.items()}

def _outfit_terms():
    """Activity and outfit names live with LAFA's personality data."""
    from .personality import OUTFIT_TEXT, OUTFIT_NAMES
    for code in CATALOG:
        CATALOG[code].update({key:entry[0] for key,entry in OUTFIT_TEXT[code].items()})
        CATALOG[code].update(OUTFIT_NAMES[code])
_outfit_terms()

def tr(lang,key):return CATALOG.get(lang,CATALOG['en']).get(key,key)
