"""Small reviewed UI catalogue; content replies follow the selected language."""
STRINGS = {
"en": ["Your desktop learning companion", "Conversation", "My files", "Learn & research", "AI services", "Settings", "Ask LAFA…", "Send", "Listen · 8s", "Read aloud", "Online", "Offline · LAFA is paused", "Find", "Open", "Read document", "Search topic…", "Search filename…", "All files", "Documents", "Music", "Videos", "Pictures", "Provider", "Model ID", "API key", "Save settings", "Show desktop companion", "Allow walking on desktop", "Read answers aloud", "Language", "New conversation", "I’m LAFA. What would you like to learn today?", "I can help you learn, find your files, explore sources, and talk things through.", "Internet is required. Connect to resume LAFA.", "AI replies need an API key and a model in Settings. Search and AI service links are available without a key.", "Open / sign in", "Search on web", "Send this document to AI?", "Selected text will be sent to your selected provider. Review it first.", "Secure keyring", "Add folder", "Remove folder", "Ready", "Working…", "Stop voice", "Local document preview", "Summarize with AI", "API requests may use paid credits. Browser sign-in is separate.", "Pause animations", "Show LAFA", "Quit", "Supported files: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Results", "No matching files.", "Search stopped at its time or result limit; narrow the query.", "Export conversation", "Clear saved key", "Mood", "Idle", "Reading", "Thinking", "Walking", "Sitting", "Gaming", "Serious", "Angry", "Talking"],
"id": ["Teman belajar di desktop Anda", "Percakapan", "File saya", "Belajar & riset", "Layanan AI", "Pengaturan", "Tanya LAFA…", "Kirim", "Dengarkan · 8 dtk", "Baca bersuara", "Terhubung", "Offline · LAFA dijeda", "Cari", "Buka", "Baca dokumen", "Cari topik…", "Cari nama file…", "Semua file", "Dokumen", "Musik", "Video", "Gambar", "Penyedia", "ID model", "API key", "Simpan pengaturan", "Tampilkan karakter desktop", "Izinkan berjalan di desktop", "Bacakan jawaban", "Bahasa", "Percakapan baru", "Saya LAFA. Apa yang ingin Anda pelajari hari ini?", "Saya bisa membantu belajar, mencari file, menelusuri sumber, dan mendengarkan cerita Anda.", "Internet diperlukan. Hubungkan untuk melanjutkan LAFA.", "Jawaban AI memerlukan API key dan model di Pengaturan. Pencarian dan tautan layanan AI tersedia tanpa key.", "Buka / login", "Cari di web", "Kirim dokumen ini ke AI?", "Teks yang dipilih akan dikirim ke penyedia Anda. Tinjau terlebih dahulu.", "Keyring aman", "Tambah folder", "Hapus folder", "Siap", "Sedang bekerja…", "Hentikan suara", "Pratinjau dokumen lokal", "Ringkas dengan AI", "Permintaan API dapat memakai kredit berbayar. Login browser terpisah.", "Jeda animasi", "Tampilkan LAFA", "Keluar", "Format: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Hasil", "Tidak ada file yang cocok.", "Pencarian mencapai batas waktu atau hasil; persempit kata pencarian.", "Ekspor percakapan", "Hapus key tersimpan", "Ekspresi", "Santai", "Membaca", "Berpikir", "Berjalan", "Duduk", "Bermain", "Serius", "Marah", "Berbicara"],
"pt": ["O seu companheiro de aprendizagem", "Conversa", "Os meus ficheiros", "Aprender e pesquisar", "Serviços de IA", "Definições", "Pergunte ao LAFA…", "Enviar", "Ouvir · 8s", "Ler em voz alta", "Ligado", "Sem internet · LAFA em pausa", "Procurar", "Abrir", "Ler documento", "Procurar tema…", "Procurar ficheiro…", "Todos os ficheiros", "Documentos", "Música", "Vídeos", "Imagens", "Fornecedor", "ID do modelo", "Chave API", "Guardar definições", "Mostrar personagem no ambiente de trabalho", "Permitir caminhar", "Ler respostas em voz alta", "Idioma", "Nova conversa", "Sou o LAFA. O que gostaria de aprender hoje?", "Posso ajudar a aprender, encontrar ficheiros, explorar fontes e conversar.", "É necessária internet. Ligue-se para continuar.", "As respostas de IA precisam de chave API e modelo nas Definições. A pesquisa e os links funcionam sem chave.", "Abrir / iniciar sessão", "Pesquisar na web", "Enviar este documento à IA?", "O texto selecionado será enviado ao fornecedor. Reveja-o primeiro.", "Porta-chaves seguro", "Adicionar pasta", "Remover pasta", "Pronto", "A trabalhar…", "Parar voz", "Pré-visualização local", "Resumir com IA", "A API pode utilizar créditos pagos. O início de sessão no navegador é separado.", "Pausar animações", "Mostrar LAFA", "Sair", "Formatos: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Resultados", "Nenhum ficheiro encontrado.", "A pesquisa atingiu o limite; reduza o âmbito.", "Exportar conversa", "Apagar chave guardada", "Expressão", "Tranquilo", "A ler", "A pensar", "A caminhar", "Sentado", "A jogar", "Sério", "Zangado", "A falar"],
"tet": ["Ita-nia belun aprendizajen iha desktop", "Konversa", "Ha'u-nia ficheiru", "Aprende no peskiza", "Servisu AI", "Konfigurasaun", "Husu LAFA…", "Haruka", "Rona · 8s", "Lee ho lian", "Konektadu", "Internet la iha · LAFA para", "Buka", "Loke", "Lee dokumentu", "Buka tópiku…", "Buka naran ficheiru…", "Ficheiru hotu", "Dokumentu", "Múzika", "Vídeu", "Imajen", "Fornesedór", "ID modelu", "Xave API", "Rai konfigurasaun", "Hatudu karakter iha desktop", "Permite la'o iha desktop", "Lee resposta ho lian", "Lian", "Konversa foun", "Ha'u LAFA. Ita hakarak aprende saida ohin?", "Ha'u bele ajuda aprende, buka ficheiru, peskiza fonte no rona ita-nia istória.", "Presiza internet. Konekta atu kontinua LAFA.", "Resposta AI presiza xave API no modelu iha Konfigurasaun. Peskiza no ligasaun AI bele uza sein xave.", "Loke / tama konta", "Buka iha web", "Haruka dokumentu ne'e ba AI?", "Testu ne'ebé hili sei haruka ba fornesedór. Haree uluk.", "Keyring seguru", "Aumenta pasta", "Hasai pasta", "Prontu", "Halo hela…", "Para lian", "Haree dokumentu lokál", "Halo rezumu ho AI", "API bele uza kréditu selu. Login iha browser ketak.", "Para animasaun", "Hatudu LAFA", "Sai", "Formatu: TXT, MD, CSV, HTML, DOCX, ODT, PDF (pdftotext).", "Rezultadu", "La hetan ficheiru.", "Peskiza to'o limite; hatún ámbitu.", "Esporta konversa", "Hasai xave rai", "Espresaun", "Kalmu", "Lee hela", "Hanoin hela", "La'o hela", "Tuur", "Joga hela", "Sériu", "Hirus", "Ko'alia"],
}
KEYS = ["tagline","chat","files","learn","hub","settings","ask","send","listen","speak","online","offline","find","open","read","topic","filename","all","documents","music","videos","pictures","provider","model","key","save","companion","roam","autoread","language","new","hello","intro","neednet","needkey","login","web","confirmdoc","confirmtext","keyring","addfolder","removefolder","ready","working","stopvoice","preview","summarize","cost","pause","show","quit","formats","results","empty","limited","export","clearkey","mood","idle","reading","thinking","walking","sitting","gaming","serious","angry","talking"]


EXTRA = {
'en':{'virtual':'Desktop assistant','live':'Weather & news','weather':'Weather','news':'World news','reminders':'Reminders','focus':'Focus · 25 min','fullwindow':'Full window','hide':'Hide bubble','sleeping':'Sleeping','bathing':'Bathing','toilet':'Toilet','studying':'Studying','eating':'Eating','stretching':'Stretching','city':'Home city','coords':'Coordinates (lat, lon)','personal':'Include bathing / toilet activities','idlehelp':'Idle activities change every 60 seconds.','addreminder':'Add reminder','minutes':'Minutes','remindertext':'What should I remind you about?','cancelreminder':'Cancel selected','sessionreminder':'Reminders work while LAFA is running; they are not saved after exit.','choosecity':'Choose the exact location','source_search':'Search a selected site','details':'Details / sources','welcome_desktop':'Hi, I’m LAFA, your Edukasaun OS assistant. Ask a question or choose weather, news, or focus.'},
'id':{'virtual':'Asisten desktop','live':'Cuaca & berita','weather':'Cuaca','news':'Berita dunia','reminders':'Pengingat','focus':'Fokus · 25 menit','fullwindow':'Jendela lengkap','hide':'Tutup balon','sleeping':'Tidur','bathing':'Mandi','toilet':'Toilet','studying':'Belajar','eating':'Makan','stretching':'Peregangan','city':'Kota utama','coords':'Koordinat (lat, lon)','personal':'Sertakan aktivitas mandi / toilet','idlehelp':'Aktivitas berganti setiap 60 detik saat tidak digunakan.','addreminder':'Tambah pengingat','minutes':'Menit','remindertext':'Apa yang perlu saya ingatkan?','cancelreminder':'Batalkan pilihan','sessionreminder':'Pengingat bekerja selama LAFA berjalan; tidak disimpan setelah keluar.','choosecity':'Pilih lokasi yang tepat','source_search':'Cari di situs pilihan','details':'Detail / sumber','welcome_desktop':'Halo, saya LAFA, asisten Edukasaun OS Anda. Tanyakan sesuatu atau pilih cuaca, berita, atau fokus.'},
'pt':{'virtual':'Assistente no desktop','live':'Tempo e notícias','weather':'Tempo','news':'Notícias do mundo','reminders':'Lembretes','focus':'Foco · 25 min','fullwindow':'Janela completa','hide':'Fechar balão','sleeping':'A dormir','bathing':'A tomar banho','toilet':'Casa de banho','studying':'A estudar','eating':'A comer','stretching':'Alongamentos','city':'Cidade principal','coords':'Coordenadas (lat, lon)','personal':'Incluir banho / casa de banho','idlehelp':'As atividades mudam a cada 60 segundos de inatividade.','addreminder':'Adicionar lembrete','minutes':'Minutos','remindertext':'O que devo lembrar?','cancelreminder':'Cancelar seleção','sessionreminder':'Lembretes funcionam enquanto o LAFA está aberto; não são guardados após sair.','choosecity':'Escolha a localização exata','source_search':'Pesquisar no site escolhido','details':'Detalhes / fontes','welcome_desktop':'Olá, sou o LAFA, o seu assistente Edukasaun OS. Pergunte ou escolha tempo, notícias ou foco.'},
'tet':{'virtual':'Asistente desktop','live':'Tempu no notísia','weather':'Tempu','news':'Notísia mundu','reminders':'Lembransa','focus':'Foku · 25 min','fullwindow':'Janela kompletu','hide':'Taka balaun','sleeping':'Toba','bathing':'Hariis','toilet':'Toalete','studying':'Estuda','eating':'Han','stretching':'Estika isin','city':'Sidade prinsipál','coords':'Koordenada (lat, lon)','personal':'Inklui hariis / toalete','idlehelp':'Atividade troka kada 60 segundu bainhira la uza.','addreminder':'Aumenta lembransa','minutes':'Minutu','remindertext':'Presiza fó lembransa kona-ba saida?','cancelreminder':'Kansela hili','sessionreminder':'Lembransa funsiona bainhira LAFA loke; la rai depois sai.','choosecity':'Hili fatin ne’ebé loos','source_search':'Buka iha sítiu hili','details':'Detallu / fonte','welcome_desktop':'Olá, ha’u LAFA, ita-nia asistente Edukasaun OS. Husu ka hili tempu, notísia ka foku.'},
}

# New 0.3 UI strings; executable source and build documentation use English.
NEW={
'en':{'desktop':'LAFA Desktop','virtual':'LAFA Virtual Assistant','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Activate LAFA Virtual Assistant in Eduka-Desktop','traditional':'Timor-Leste traditional outfit','casual':'Casual outfit','costume':'Outfit','system_language':'System default','culture':'Discover Timor-Leste','timor_news':'Timor-Leste news','coding':'Virtual Coding','run_lesson':'Run Python lesson','lesson_mode':'Bounded Python lessons: variables, arithmetic, lists, loops, conditions. No imports, files, network or system commands. JavaScript, HTML and CSS support learning and export.','save_code':'Export code','explain_code':'Explain with AI','source_mode':'Open-source knowledge mode · public source extracts, not model-generated reasoning.','positive':'Positive messages','culture_cards':'Timor-Leste knowledge cards','local_updates':'Timor-Leste news updates','panel_walk':'Walk back and forth above the panel','panel_edge':'Panel edge','panel_height':'Panel height (px)','card_interval':'Cards / positive messages (minutes)','news_interval':'News interval (minutes)','welcome_virtual':'I’m LAFA, from Timor-Leste, a virtual assistant ready to help you. Let’s learn and discover together!','learning_ready':'Ready to learn.','priority':'Priority topics','education':'Education','arts_culture':'Arts & culture','development':'Development','technology':'Technology','open_settings':'Open LAFA settings','source':'Source','source_dates':'Source-linked cards checked on 6 October 2026. Explore more online.','refresh':'Refresh','pause_popups':'Cards and positive messages appear only when LAFA is idle.','disabled_virtual':'Virtual Assistant is disabled. Enable it in LAFA · Eduka-Settings.','tebe':'Tebe-tebe dance','bidu':'Bidu dance'},
'id':{'desktop':'LAFA Desktop','virtual':'LAFA Asisten Virtual','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Aktifkan LAFA Asisten Virtual di Eduka-Desktop','traditional':'Pakaian adat Timor-Leste','casual':'Pakaian santai','costume':'Pakaian','system_language':'Bahasa sistem','culture':'Kenali Timor-Leste','timor_news':'Berita Timor-Leste','coding':'Coding Virtual','run_lesson':'Jalankan pelajaran Python','lesson_mode':'Python terbatas: variabel, aritmetika, daftar, perulangan, kondisi. Tanpa impor, file, jaringan atau perintah sistem. JavaScript, HTML dan CSS untuk belajar dan ekspor.','save_code':'Ekspor kode','explain_code':'Jelaskan dengan AI','source_mode':'Mode pengetahuan sumber terbuka · cuplikan sumber publik, tanpa penalaran model AI.','positive':'Pesan positif','culture_cards':'Kartu pengetahuan Timor-Leste','local_updates':'Pembaruan berita Timor-Leste','panel_walk':'Berjalan bolak-balik di atas panel','panel_edge':'Sisi panel','panel_height':'Tinggi panel (px)','card_interval':'Kartu / pesan positif (menit)','news_interval':'Interval berita (menit)','welcome_virtual':'Saya LAFA, dari Timor-Leste, asisten virtual yang siap membantu Anda. Mari belajar dan menjelajah bersama!','learning_ready':'Siap belajar.','priority':'Topik utama','education':'Pendidikan','arts_culture':'Seni & budaya','development':'Pembangunan','technology':'Teknologi','open_settings':'Buka pengaturan LAFA','source':'Sumber','source_dates':'Kartu bersumber diperiksa pada 6 Oktober 2026. Jelajahi lebih lanjut di internet.','refresh':'Perbarui','pause_popups':'Kartu dan pesan positif muncul hanya saat LAFA tidak digunakan.','disabled_virtual':'Asisten Virtual dinonaktifkan. Aktifkan melalui LAFA · Eduka-Settings.','tebe':'Tari Tebe-tebe','bidu':'Tari Bidu'},
'pt':{'desktop':'LAFA Desktop','virtual':'Assistente Virtual LAFA','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Ativar o Assistente Virtual LAFA no Eduka-Desktop','traditional':'Traje tradicional de Timor-Leste','casual':'Traje informal','costume':'Traje','system_language':'Idioma do sistema','culture':'Conhecer Timor-Leste','timor_news':'Notícias de Timor-Leste','coding':'Programação Virtual','run_lesson':'Executar lição Python','lesson_mode':'Python limitado: variáveis, aritmética, listas, ciclos e condições. Sem importações, ficheiros, rede ou comandos de sistema. JavaScript, HTML e CSS para aprender e exportar.','save_code':'Exportar código','explain_code':'Explicar com IA','source_mode':'Modo de conhecimento aberto · excertos de fontes públicas, sem raciocínio de um modelo.','positive':'Mensagens positivas','culture_cards':'Cartões sobre Timor-Leste','local_updates':'Atualizações de notícias timorenses','panel_walk':'Caminhar junto ao painel','panel_edge':'Posição do painel','panel_height':'Altura do painel (px)','card_interval':'Cartões / mensagens (minutos)','news_interval':'Intervalo de notícias (minutos)','welcome_virtual':'Sou o LAFA, de Timor-Leste, um assistente virtual pronto para ajudar. Vamos aprender e descobrir juntos!','learning_ready':'Pronto para aprender.','priority':'Temas prioritários','education':'Educação','arts_culture':'Arte e cultura','development':'Desenvolvimento','technology':'Tecnologia','open_settings':'Abrir definições LAFA','source':'Fonte','source_dates':'Fontes verificadas em 6 de outubro de 2026. Explore mais online.','refresh':'Atualizar','pause_popups':'Cartões e mensagens aparecem apenas durante a inatividade.','disabled_virtual':'Assistente Virtual desativado. Ative em LAFA · Eduka-Settings.','tebe':'Dança Tebe-tebe','bidu':'Dança Bidu'},
 'tet':{'desktop':'LAFA Desktop','virtual':'LAFA Asistente Virtuál','lafa_settings':'LAFA · Eduka-Settings','activate_virtual':'Ativa LAFA Asistente Virtuál iha Eduka-Desktop','traditional':'Hatais tradisionál Timor-Leste','casual':'Hatais simples','costume':'Hatais','system_language':'Lian sistema nian','culture':'Koñese Timor-Leste','timor_news':'Notísia Timor-Leste','coding':'Kodifikasaun Virtuál','run_lesson':'Halo lisaun Python','lesson_mode':'Python ho limite: variavel, aritmétika, lista, siklu no kondisaun. La iha importasaun, ficheiru, rede ka komandu sistema. JavaScript, HTML no CSS ba aprende no esporta.','save_code':'Esporta kódigu','explain_code':'Esplika ho AI','source_mode':'Koñesimentu fonte aberta · testu fonte públika, sein modelu AI.','positive':'Mensajen pozitivu','culture_cards':'Karta koñesimentu Timor-Leste','local_updates':'Atualizasaun notísia Timor-Leste','panel_walk':'La’o ba-mai iha painel leten','panel_edge':'Pozisaun painel','panel_height':'Altura painel (px)','card_interval':'Karta / mensajen (minutu)','news_interval':'Intervalu notísia (minutu)','welcome_virtual':'Ha’u LAFA, husi Timor-Leste, asistente virtuál ne’ebé prontu atu ajuda ita. Mai aprende no deskobre hamutuk!','learning_ready':'Prontu atu aprende.','priority':'Tópiku prinsipál','education':'Edukasaun','arts_culture':'Arte no kultura','development':'Dezenvolvimentu','technology':'Teknolojia','open_settings':'Loke konfigurasaun LAFA','source':'Fonte','source_dates':'Fonte verifika iha 6 Outubru 2026. Buka tan iha internet.','refresh':'Atualiza','pause_popups':'Karta no mensajen mosu de’it bainhira LAFA la uza.','disabled_virtual':'Asistente Virtuál la ativu. Ativa iha LAFA · Eduka-Settings.','tebe':'Dansa Tebe-tebe','bidu':'Dansa Bidu'}
}

# Release 0.4 common interface text. Translations are data, not executable code.
RELEASE={
'en':{
'public_search':'Search public sources','public_hint':'Send this question to Wikipedia. Use public topics; do not include private information.',
'source_help':'I can help you find public sources, read documents, check weather and news, and practice coding without an AI key. For a public question, use Search public sources or /ask topic. Your ordinary chat text is not automatically sent to Wikipedia. A configured AI provider enables fuller conversation.',
'source_mode':'Public source mode · use Search public sources to send a question to Wikipedia.','no_public_results':'No matching public sources. Try a shorter topic.',
'pet_help':'LAFA · click to chat · drag to move · right click for activities',
'virtual_settings':'Virtual Assistant','connections':'AI & language','files_weather':'Files & weather','bottom':'Bottom','top':'Top',
'api_ready':'API configured','api_missing':'API not configured','session_key':'New key · session only unless secure keyring is selected',
'model_hint':'Official model ID · Perplexity uses the fast preset','voice_note':'Tetun read-aloud uses Portuguese pronunciation. A native Tetun voice is not bundled.',
'wayland_note':'Automatic panel walking needs X11. Wayland allows manual placement controlled by the compositor.',
'key_external':'Environment keys are managed outside LAFA.','timezone':'Timezone · IANA / auto',
'you':'YOU','file_type':'Type','folder':'Folder','scanned':'scanned','source_title':'Source','summary':'Summary',
'public_library':'Wikipedia · public source search','compare_sources':'Read the source, compare facts, and ask LAFA for an explanation.',
'learning_library':'LEARNING LIBRARY','article_hint':'Wikipedia snippets; use Read for article introductions.',
'browser_login_note':'Sign in through your default browser. LAFA does not store website passwords or sessions.',
'headline':'Headline','publisher':'Publisher','published':'Published (UTC)','filter_headlines':'Filter headlines · optional','retrieved':'Retrieved','unavailable':'Unavailable',
'no_headlines':'No matching headlines.','headlines':'headlines','no_topic_news':'No matching topics in this feed window.',
'lesson_steps':'lesson steps','transcribe_question':'Record 8 seconds and send the audio to OpenAI for transcription?',
'voice_key':'Voice input requires an OpenAI API key. Add it in LAFA Settings.',
'review_banner':'REVIEW MODE · sample content · no API call','preview_only':'Review mode: no live requests.',
'review_chat':'Review mode is for visual inspection. Run LAFA normally to use public sources or configure an AI provider.',
'need_city':'Enter the home city name.','query_limit':'Use one public topic of at most 300 characters.',
},
'id':{
'public_search':'Cari sumber publik','public_hint':'Kirim pertanyaan ini ke Wikipedia. Gunakan topik publik; jangan sertakan informasi pribadi.',
'source_help':'Saya bisa membantu mencari sumber publik, membaca dokumen, melihat cuaca dan berita, serta latihan coding tanpa API key. Untuk pertanyaan publik, pilih Cari sumber publik atau /ask topik. Teks chat biasa tidak otomatis dikirim ke Wikipedia. Penyedia AI memungkinkan percakapan lebih lengkap.',
'source_mode':'Mode sumber publik · pilih Cari sumber publik untuk mengirim pertanyaan ke Wikipedia.','no_public_results':'Tidak ada sumber publik yang cocok. Coba topik lebih singkat.',
'pet_help':'LAFA · klik untuk berbicara · seret untuk memindahkan · klik kanan untuk aktivitas',
'virtual_settings':'Asisten Virtual','connections':'AI & bahasa','files_weather':'File & cuaca','bottom':'Bawah','top':'Atas',
'api_ready':'API dikonfigurasi','api_missing':'API belum dikonfigurasi','session_key':'Key baru · hanya sesi kecuali keyring aman dipilih',
'model_hint':'ID model resmi · Perplexity memakai preset fast','voice_note':'Baca bersuara Tetun memakai pelafalan Portugis. Suara Tetun asli belum disertakan.',
'wayland_note':'Berjalan otomatis di panel memerlukan X11. Wayland memakai penempatan manual oleh compositor.',
'key_external':'Key environment dikelola di luar LAFA.','timezone':'Zona waktu · IANA / auto',
'you':'ANDA','file_type':'Jenis','folder':'Folder','scanned':'dipindai','source_title':'Sumber','summary':'Ringkasan',
'public_library':'Wikipedia · pencarian sumber publik','compare_sources':'Baca sumber, bandingkan fakta, lalu minta penjelasan LAFA.',
'learning_library':'PUSTAKA BELAJAR','article_hint':'Cuplikan Wikipedia; pilih Baca untuk pengantar artikel.',
'browser_login_note':'Login melalui browser bawaan. LAFA tidak menyimpan kata sandi atau sesi situs.',
'headline':'Judul berita','publisher':'Penerbit','published':'Dipublikasikan (UTC)','filter_headlines':'Filter judul · opsional','retrieved':'Diambil','unavailable':'Tidak tersedia',
'no_headlines':'Tidak ada judul yang cocok.','headlines':'judul berita','no_topic_news':'Tidak ada topik yang cocok dalam feed ini.',
'lesson_steps':'langkah pelajaran','transcribe_question':'Rekam 8 detik dan kirim audio ke OpenAI untuk transkripsi?',
'voice_key':'Input suara memerlukan API key OpenAI. Tambahkan di Pengaturan LAFA.',
'review_banner':'MODE REVIEW · contoh konten · tanpa panggilan API','preview_only':'Mode review: tidak mengambil data langsung.',
'review_chat':'Mode review untuk meninjau tampilan. Jalankan LAFA normal untuk memakai sumber publik atau mengatur penyedia AI.',
'need_city':'Masukkan nama kota utama.','query_limit':'Gunakan satu topik publik maksimal 300 karakter.',
},
'pt':{
'public_search':'Pesquisar fontes públicas','public_hint':'Enviar a pergunta à Wikipedia. Use temas públicos; não inclua informação privada.',
'source_help':'Posso procurar fontes públicas, ler documentos, consultar tempo e notícias e praticar programação sem chave API. Para uma pergunta pública, use Pesquisar fontes públicas ou /ask tema. O texto normal da conversa não é enviado automaticamente à Wikipedia. Um fornecedor de IA permite uma conversa mais completa.',
'source_mode':'Modo de fontes públicas · use Pesquisar fontes públicas para enviar uma pergunta à Wikipedia.','no_public_results':'Nenhuma fonte pública corresponde. Tente um tema mais curto.',
'pet_help':'LAFA · clique para conversar · arraste para mover · botão direito para atividades',
'virtual_settings':'Assistente Virtual','connections':'IA e idioma','files_weather':'Ficheiros e tempo','bottom':'Inferior','top':'Superior',
'api_ready':'API configurada','api_missing':'API não configurada','session_key':'Nova chave · só nesta sessão, salvo porta-chaves seguro',
'model_hint':'ID oficial do modelo · Perplexity usa o preset fast','voice_note':'A leitura em Tetun usa pronúncia portuguesa. Não está incluída uma voz nativa de Tetun.',
'wayland_note':'Caminhar automaticamente no painel exige X11. Em Wayland a posição manual depende do compositor.',
'key_external':'As chaves de ambiente são geridas fora do LAFA.','timezone':'Fuso horário · IANA / auto',
'you':'VOCÊ','file_type':'Tipo','folder':'Pasta','scanned':'analisados','source_title':'Fonte','summary':'Resumo',
'public_library':'Wikipedia · pesquisa de fontes públicas','compare_sources':'Leia a fonte, compare os factos e peça uma explicação ao LAFA.',
'learning_library':'BIBLIOTECA DE APRENDIZAGEM','article_hint':'Excertos da Wikipedia; use Ler para introduções dos artigos.',
'browser_login_note':'Inicie sessão no navegador predefinido. LAFA não guarda palavras-passe nem sessões dos sites.',
'headline':'Título','publisher':'Editor','published':'Publicado (UTC)','filter_headlines':'Filtrar títulos · opcional','retrieved':'Obtido','unavailable':'Indisponível',
'no_headlines':'Nenhum título corresponde.','headlines':'títulos','no_topic_news':'Nenhum tema corresponde nesta janela do feed.',
'lesson_steps':'passos da lição','transcribe_question':'Gravar 8 segundos e enviar o áudio à OpenAI para transcrição?',
'voice_key':'A entrada de voz exige uma chave API OpenAI. Adicione-a nas Definições LAFA.',
'review_banner':'MODO DE REVISÃO · exemplos · sem chamada API','preview_only':'Modo de revisão: sem pedidos de dados em direto.',
'review_chat':'Modo de revisão para inspecionar a interface. Execute LAFA normalmente para usar fontes públicas ou configurar um fornecedor de IA.',
'need_city':'Introduza o nome da cidade principal.','query_limit':'Use um tema público até 300 caracteres.',
},
 'tet':{
'public_search':'Buka fonte públika','public_hint':'Haruka pergunta ba Wikipedia. Uza tópiku públiku; la inklui informasaun privada.',
'source_help':"Ha'u bele buka fonte públika, lee dokumentu, haree tempu no notísia no aprende kódigu sein xave API. Ba pergunta públika, uza Buka fonte públika ka /ask tópiku. Testu konversa normál la haruka automaticamente ba Wikipedia. Provedor IA permite konversa kompletu liu.",
'source_mode':'Modu fonte públika · uza Buka fonte públika atu haruka pergunta ba Wikipedia.','no_public_results':'La hetan fonte públika ne’ebé loos. Koko tópiku badak liu.',
'pet_help':'LAFA · klik atu ko’alia · dada atu muda fatin · klik direita ba atividade',
'virtual_settings':'Asistente Virtuál','connections':'IA no lian','files_weather':'Ficheiru no tempu','bottom':'Iha kraik','top':'Iha leten',
'api_ready':'API konfigura ona','api_missing':'API seidauk konfigura','session_key':'Xave foun · ba sesaun de’it ka keyring seguru',
'model_hint':'ID modelu ofisiál · Perplexity uza preset fast','voice_note':'Lee Tetun ho lian uza pronúnsia Portugés. Lian Tetun nativu seidauk inklui.',
'wayland_note':'La’o automaticamente iha painel presiza X11. Iha Wayland, compositor kontrola fatin manuál.',
'key_external':'Xave environment jere iha liur LAFA.','timezone':'Zona tempu · IANA / auto',
'you':'ITA','file_type':'Tipu','folder':'Pasta','scanned':'haree ona','source_title':'Fonte','summary':'Rezumu',
'public_library':'Wikipedia · buka fonte públika','compare_sources':'Lee fonte, kompara faktu no husu LAFA atu esplika.',
'learning_library':'BIBLIOTEKA APRENDIZAJEN','article_hint':'Rezumu Wikipedia; uza Lee ba introdusaun artigu.',
'browser_login_note':'Tama konta iha browser padraun. LAFA la rai senha ka sesaun sítiu.',
'headline':'Títulu notísia','publisher':'Publikadór','published':'Publika (UTC)','filter_headlines':'Filtra títulu · opsionál','retrieved':'Hetan','unavailable':'La disponivel',
'no_headlines':'La hetan títulu ne’ebé loos.','headlines':'títulu notísia','no_topic_news':'La hetan tópiku ne’ebé loos iha feed ne’e.',
'lesson_steps':'pasu lisaun','transcribe_question':'Grava segundu 8 no haruka áudio ba OpenAI atu halo transkrisaun?',
'voice_key':'Input lian presiza xave API OpenAI. Aumenta iha Konfigurasaun LAFA.',
'review_banner':'MODU REVIZAUN · ezemplu · sein chamada API','preview_only':'Modu revizaun: la husu dadus diretu.',
'review_chat':'Modu revizaun ba haree interface. Loke LAFA normál atu uza fonte públika ka konfigura provedor IA.',
'need_city':'Hakerek naran sidade prinsipál.','query_limit':'Uza tópiku públiku ida ho karakter to’o 300.',
}}

_RELEASE_EXTRAS={
'en':{'hub_chat_learning':'Chat & learning','hub_multimodal':'Chat & multimodal','hub_writing':'Writing & code','hub_chat_search':'Chat & search','hub_reasoning':'Chat & reasoning','hub_research':'Research & search','hub_notes':'Notes & sources','hub_images':'Images','hub_media':'Creative media','hub_voice':'Voice & audio','hub_code':'Coding','hub_apps':'Apps & websites','lesson_hello':'Hello, Timor-Leste','lesson_variables':'Variables and arithmetic','lesson_loops':'Loops','lesson_conditions':'Conditions','lesson_browser':'Browser basics','lesson_html':'My learning page','lesson_css':'Style a learning page'},
'id':{'hub_chat_learning':'Percakapan & belajar','hub_multimodal':'Percakapan & multimodal','hub_writing':'Menulis & kode','hub_chat_search':'Percakapan & pencarian','hub_reasoning':'Percakapan & penalaran','hub_research':'Riset & pencarian','hub_notes':'Catatan & sumber','hub_images':'Gambar','hub_media':'Media kreatif','hub_voice':'Suara & audio','hub_code':'Coding','hub_apps':'Aplikasi & situs','lesson_hello':'Halo, Timor-Leste','lesson_variables':'Variabel dan aritmetika','lesson_loops':'Perulangan','lesson_conditions':'Kondisi','lesson_browser':'Dasar browser','lesson_html':'Halaman belajar saya','lesson_css':'Gaya halaman belajar'},
'pt':{'hub_chat_learning':'Conversa e aprendizagem','hub_multimodal':'Conversa e multimodal','hub_writing':'Escrita e código','hub_chat_search':'Conversa e pesquisa','hub_reasoning':'Conversa e raciocínio','hub_research':'Investigação e pesquisa','hub_notes':'Notas e fontes','hub_images':'Imagens','hub_media':'Media criativos','hub_voice':'Voz e áudio','hub_code':'Programação','hub_apps':'Aplicações e sites','lesson_hello':'Olá, Timor-Leste','lesson_variables':'Variáveis e aritmética','lesson_loops':'Ciclos','lesson_conditions':'Condições','lesson_browser':'Noções do navegador','lesson_html':'A minha página de aprendizagem','lesson_css':'Estilo de uma página'},
 'tet':{'hub_chat_learning':'Konversa no aprendizajen','hub_multimodal':'Konversa no multimodál','hub_writing':'Hakerek no kódigu','hub_chat_search':'Konversa no peskiza','hub_reasoning':'Konversa no hanoin','hub_research':'Investigasaun no peskiza','hub_notes':'Nota no fonte','hub_images':'Imajen','hub_media':'Mídia kriativu','hub_voice':'Lian no áudio','hub_code':'Programasaun','hub_apps':'Aplikasaun no sítiu','lesson_hello':'Olá, Timor-Leste','lesson_variables':'Variavel no aritmétika','lesson_loops':'Repetisaun','lesson_conditions':'Kondisaun','lesson_browser':'Baze browser','lesson_html':'Ha’u-nia pájina aprendizajen','lesson_css':'Estilu pájina aprendizajen'},
}
for _language,_entries in _RELEASE_EXTRAS.items():RELEASE[_language].update(_entries)

CATALOG={code:{**dict(zip(KEYS,strings)),**EXTRA[code],**NEW[code],**RELEASE[code]} for code,strings in STRINGS.items()}

def tr(lang,key):return CATALOG.get(lang,CATALOG['en']).get(key,key)
